### ISSUE TITLE
Couldn't find any versions for "@grafana/faro-web-sdk" that matches "^1.0.0-beta6"

### ISSUE THREAD

**Issue by sonam0211** [grafana/faro-web-sdk#105]
**Description**
"@grafana/faro-web-sdk"  "^1.0.0-beta6" is not available on npm to use `faro.api.setView()`

**Steps to reproduce**
Update "@grafana/faro-web-sdk" version to ^1.0.0-beta6 and run npm

**Expected behavior**
"@grafana/faro-web-sdk" version to ^1.0.0-beta6 should be updated

**Actual behavior**
```
Couldn't find any versions for "@grafana/faro-web-sdk" that matches "^1.0.0-beta6"
? Please choose a version of "@grafana/faro-web-sdk" from this list: 
❯ 1.0.0-beta4 
  1.0.0-beta3 
  1.0.0-beta2 
  1.0.0-beta1 
```

**Comment by codecapitano** [comment]
Hi @sonam0211 

Faro is now updated on npm (v1.0.0) and the current version should be available.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/47627413/222139894-4dd8f65f-f5cf-4b09-a44a-cf74422c0150.png">
