### ISSUE TITLE
Align measurement payload to only be able to contain  exactly one measurement.

### ISSUE THREAD

**Issue by codecapitano** [grafana/faro-web-sdk#110]
The Otel spec says that we don't have multiple metrics in the same scoped resource.

In Faro it is possible to add  more then one metric type to the measurements array.
The original intention was to be able to log different metrics which belong to the same type in one line.
But, we never used this variant an in the current Faro implementation we create a single log line for each metric because we call `pushMeasuerent` for each. 

For example the  WebVitals transport. Here we call `pushMeasurement` for each WV which will translate into one measurement for each Web Vital.

Example payload WebVitals:
```js
"measurements": [
    { "type": "web-vitals", "values": { "fcp": 213.7000000011176 } }
  ],
```

We need to change this in way so that a paylaod only contains one metric.
Fro example: 

```js
measurementPayload: {
    type: 'web-vitals',
    name: 'fcp'
    value: '1.234'
}
```

**Comment by eskirk** [comment]
@codecapitano accidental re-open? if so lets move it to done

**Comment by codecapitano** [comment]
Yes we can close this
