### ISSUE TITLE
Dart / Flutter SDK

### ISSUE THREAD

**Issue by code-byAk** [grafana/faro-web-sdk#115]
## Description

We need to know if there is any plan to come up with a Mobile SDK for RUM and if there is what is the road-map and estimated time-line when we can expect an important feature release like this.

**Comment by codecapitano** [comment]
Hi @code-byAk thank you for your question.

Currently as well as midterm we don't have the Mobile SDK in scope.
So at the moment we can't provide an estimate about when it will land.

Thank you and cheers,
Marco

cc @cedricziel
