### ISSUE TITLE
Add option to disable/enable Faro on headless Browsers

### ISSUE THREAD

**Issue by codecapitano** [grafana/faro-web-sdk#123]
## Description
Sometimes headless browsers may be used for example to do background actions like loading a page and screenshot it.
For such cases it is not needed to Faro into headless browser.
It also can lead to strange behavior in the worst case.

## Proposed solution
* Disable Faro for headless browsers by default
* Make it configurable so people can enable Faro on headless browsers if needed.

**Comment by domasx2** [comment]
TBH I don't think we should disable it by default for headless, it might be useful for these cases

**Comment by codecapitano** [comment]
Yes good hint Domas you're right we should not decide this for the user. 
Better keep out-of-box instrumentation and provide the option to disable it when needed.

**Comment by eskirk** [comment]
@codecapitano I feel like we did this? this issue was blocking a grafana release IIRC? close if so, thanks :)

**Comment by codecapitano** [comment]
Yes, no further work needed here. The problem was solved by closing requests in the FetchTransport
