### ISSUE TITLE
Add more documentation on W3CTraceContextPropagator as it is not injecting correctly traceparent header following the quickstart

### ISSUE THREAD

**Issue by AMontagu** [grafana/faro-web-sdk#131]
## Description

Documentation in quickstart to explain how to pass the current traceid (or traceparent) to backend to follow the whole user trace.

I am looking since some time on how to propagate the trace from faro in the front end to the back end. 

I read the documentation that said: 

```
Note: To link the traces from the front end with the traces from the API, the tracing instrumentation relies on a trace propagator, which by default uses W3CTraceContextPropagator. This propagator adds a traceparent header to all fetch requests which is then used by your API.
```
(https://grafana.com/docs/grafana-cloud/faro-web-sdk/faro-web-sdk-components/provided-instrumentations/)

But I didn't see any header with traceparent on my request. Using axios and grpc-web (tested on both).

Tested with both examples: 
- https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md#with-opentelemetry-tracing-using-the-included-instrumentation 
- https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md#with-custom-opentelemetry-tracing-configuration 

First one is not injecting the traceparent headers.

Second one throw an exception:
```
MultiSpanProcessor.js?57ae:76 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at FaroSessionSpanProcessor.onStart (sessionSpanProcessor.js?6d84:11:1)
    at MultiSpanProcessor.onStart (MultiSpanProcessor.js?57ae:68:1)
    at new Span (Span.js?03ea:86:1)
    at Tracer.startSpan (Tracer.js?ea0d:92:1)
    at eval (faro2.js?67fe:59:1)
    at ./src/setup/faro2.js (app.js:1138:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at eval (main.js?56d7:1:1)
    at ./src/main.js (app.js:1078:1)
```
Error fixed by changing one line from the README to: 
```
provider.addSpanProcessor(new FaroSessionSpanProcessor(new BatchSpanProcessor(new FaroTraceExporter({ faro })), {value: {session: null}}));
```

But still no traceparent in the request headers.

Also tried to add a meta with a traceparent into the index.html to test it as specified here: https://opentelemetry.io/docs/instrumentation/js/getting-started/browser/ but without sucess

But not working either.

W3CTraceContextPropagator is correctly called and the carrier is also correctly setted. but do not know which part inject the carrier into the XHR or fetch header.

## Proposed solution

Add a clear exemple of step to add the traceparent header to XHR & Fetch request.

**Comment by codecapitano** [comment]
Hi @AMontagu thanks a lot for bringing this up.

Faro excludes the endpoints which are used by it's transports. 
This is to prevent a loop of reporting on itself.

For example:
```js
const faro = initializeFaro({
  url: 'http://localhost:12345/collect',
  apiKey: 'secret',
  instrumentations: [...getWebInstrumentations(), new TracingInstrumentation()],
  app: {
    name: 'frontend',
    version: '1.0.0',
  },
});
```

For this config the collector endpoint (http://localhost:12345/collect) is excluded from tracing so you don't see a `traceparent` header there. For other endpoints you should see them added.


## Let's take the Faro Demo App ans an example 
It initializes Faro with `{ url: http://localhost:${env.faro.portAppReceiver}/collect, … }` so this url is excluded from tracing. But the request to `/api/auth/state` is instrumented and header added.

<img width="1662" alt="image (1)" src="https://user-images.githubusercontent.com/47627413/225357760-1161310c-586e-4716-94ac-1216541f88ed.png">
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/47627413/225357788-9bcb5c0a-64c2-4719-8465-60cdeab0eb6c.png">

**Comment by AMontagu** [comment]
Hello @codecapitano 

Yes I debuggued hardly everything and make it work. But except if I missed something the call to API are not adding traceparent because it miss the propagateTraceHeaderCorsUrls.

This code worked for me but I had to override the defautl instrumentations. Maybe adding a options for propagateTraceHeaderCorsUrls will be better. Without this options the traceparent headers is not added. 

See: https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts#L109 And https://github.com/open-telemetry/opentelemetry-js/blob/2276977218a589afa508ec810381bd46b35052a7/packages/opentelemetry-sdk-trace-web/src/utils.ts#L416

It only work when same origin. But if you are in a micro-service architecture without an api gateway in local it doesn't work.


```
import {trace, context} from "@opentelemetry/api";
import { getWebInstrumentations, initializeFaro } from "@grafana/faro-web-sdk";
import { TracingInstrumentation } from "@grafana/faro-web-tracing";
import { DocumentLoadInstrumentation } from "@opentelemetry/instrumentation-document-load";
import { FetchInstrumentation } from "@opentelemetry/instrumentation-fetch";
import { UserInteractionInstrumentation } from "@opentelemetry/instrumentation-user-interaction";
import { XMLHttpRequestInstrumentation } from "@opentelemetry/instrumentation-xml-http-request";
import SocioManifest from ""

// INFO - AM - 15/03/2023 - To have debug  please uncomme the next two line and comment the first one
// import {trace, context, diag, DiagConsoleLogger, DiagLogLevel} from "@opentelemetry/api";
// diag.setLogger(new DiagConsoleLogger(), DiagLogLevel.DEBUG);

const VERSION = "1.0.0";
const NAME = "test_infra_front";
const COLLECTOR_URL = "http://localhost:12349/collect";


const ignoreUrls = [COLLECTOR_URL];

const regexBack = new RegExp("http://localhost:9000/*");
const regexGRPC = new RegExp("http://localhost:50051/*");

const instrumentations = [
  new DocumentLoadInstrumentation(),
  new FetchInstrumentation({
    ignoreUrls,
    propagateTraceHeaderCorsUrls: [ // INFO - AM - 15/03/2023 - See https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts#L109 
      regexBack,
      regexGRPC,
    ]
  }),
  new XMLHttpRequestInstrumentation({
    ignoreUrls,
    propagateTraceHeaderCorsUrls: [
      regexBack,
      regexGRPC,
    ]
  }),
  new UserInteractionInstrumentation()
]

const faro = initializeFaro({
  url: COLLECTOR_URL,
  apiKey: "secret",
  instrumentations: [
    ...getWebInstrumentations(), // INFO - AM - 15/03/2023 - To see the instrucmentations look at: https://github.com/grafana/faro-web-sdk/blob/main/packages/web-sdk/src/config/getWebInstrumentations.ts
    new TracingInstrumentation({instrumentations}) // INFO - AM - 15/03/2023 - Need to override instrumentation as default config do not take propagateTraceHeaderCorsUrls that is required. https://github.com/grafana/faro-web-sdk/blob/main/packages/web-tracing/src/instrumentation.ts
  ],
  app: {
    name: NAME,
    version: VERSION
  }
});

faro.api.initOTEL(trace, context);

export default faro;
```

Will resume all issues seing in the quickstart in a separate message in this issue so you can have all of them in a small and concise way and then let you close the issue once the quickstart edited

**Comment by AMontagu** [comment]
Resume of quickstart issue:

1. The quickstart default implementation not adding traceparent in other origin than the page one
Reco: Adding an option to TracingInstrumentation constructor to pass accepted URLS and specify that a list of regex. If do not want to mix specific instrumentor options with  TracingInstrumentation add a new example that redefine the instrumentations as in my previous message.

2. The example with "With custom OpenTelemetry tracing configuration" (https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md#with-custom-opentelemetry-tracing-configuration) is not working as it miss the session

Adding in the README the logic to bring the `this.meta` see here: https://github.com/grafana/faro-web-sdk/blob/main/packages/web-tracing/src/instrumentation.ts#L56 in the quickstart or change the line by:
`provider.addSpanProcessor(new FaroSessionSpanProcessor(new BatchSpanProcessor(new FaroTraceExporter({ faro })), {value: {session: null}}));`

3. There is explicit explanation than a Faro Instrumentation and an OpenApi instrumentations are two differents logic. I tried to add `FetchInstrumentation` directly into the `instrumentations` key of `initializeFaro` before reading source code to understanc how to override it

4. There is no documentation about TracingInstrumentation config options. By reading the source code it seem more easy to use them instead of using the example "With custom OpenTelemetry tracing configuration"

**Comment by codecapitano** [comment]
Thanks so much @AMontagu. 

I assume you put in an extensive time effort into finding out and reporting as well as writing that nice   
clustered issue descriptions. Those are very good to handle.

Cheers,
 Marco

**Comment by alioshr** [comment]
Hey @codecapitano  and @AMontagu! I have used this workaround and I successfully get the ```traceparent``` header added to the requests that match the given patterns on  ```FetchInstrumentation``` and ```XMLHttpRequestInstrumentation```. 

Sorry if this has no direct relation with this lib, but will ```tracestate``` headers be also added with this solution? We also need ```tracestate``` headers added to our requests. 

Thanks in advance for the help!
