### ISSUE TITLE
Allow extra context for errors

### ISSUE THREAD

**Issue by domasx2** [grafana/faro-web-sdk#141]
## Description

Currently `faro.api.pushError()` only accepts and `Error` argument, there is no way to add extra context data.
One significant use case would be capturing React error boundary errors, where in addition to the regular stack trace
there is the component stack trace. It would be great to be able to add is as extra information. 

## Proposed solution

Add optional context parameter, same as for `faro.api.pushLog()`. Will require changes for recevier too

**Comment by codecapitano** [comment]
* [PR Web-SDK update](https://github.com/grafana/faro-web-sdk/pull/190)
* [PR Agent update](https://github.com/grafana/agent/pull/3911)
* [PR Receiver update](https://github.com/grafana/grafana-frontend-telemetry-receiver/pull/15)
