### ISSUE TITLE
Trace propagator is not adding traceparent header to fetch requests

### ISSUE THREAD

**Issue by therealmanny** [grafana/faro-web-sdk#144]
## Description
The trace propagator is not adding a `traceparent` header to fetch requests. After setting up my frontend app (React) using the [faro web SDK quick start browser tutorial](https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md) and [demo](https://github.com/grafana/faro-web-sdk/tree/main/demo). I am able to push telemetry successfully. But I can't seem to get the `traceparent` header added to fetch requests. I came across this issue #131, which seems to have the same issue I am experiencing. But changing the OpenTelemetry tracing configuration to [this](https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md#with-custom-opentelemetry-tracing-configuration) did not fix the issue I am having. Thanks for taking the time to look at this issue.

## Steps to reproduce
1. Add Faro web SDK, web tracing, and react to the project
2. Generate network traffic
3. And observe fetch request headers

## Expected behavior
Trace propagator should add a `traceparent` header to fetch requests header

## Actual behavior
`traceparent` header is not added to fetch requests header

## Environment

- **SDK version:** 1.0.2
- **SDK instrumentations:** Web SDK, Web Tracing, React
- **Device type:** Laptop
- **Device name:** Dell Precision 7550
- **OS:** Windows 10
- **Browser:** Chrome 111.0.5563.147 (Official Build) (64-bit)

## Demo
The network tab, `traceparent` is not added to request headers.

![traceparentHeaderNotAdded](https://user-images.githubusercontent.com/60148752/228967734-2f946f79-4c7a-4c80-aae6-051e9c8036a6.PNG)

#### Package.json dependencies
```json
{
  "dependencies": {
    "@beam-australia/react-env": "^3.1.1",
    "@grafana/faro-react": "^1.0.2",
    "@grafana/faro-web-sdk": "^1.0.2",
    "@grafana/faro-web-tracing": "^1.0.2",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.10.0",
    "react-scripts": "^5.0.0",
    "web-vitals": "^2.1.2"
  },
}
```

#### Faro initialization
```javascript
import {
  ConsoleTransport,
  FetchTransport,
  initializeFaro as coreInit,
  getWebInstrumentations,
  ReactIntegration,
  ReactRouterVersion
} from "@grafana/faro-react"
import { TracingInstrumentation } from "@grafana/faro-web-tracing"
import {
  createRoutesFromChildren,
  matchRoutes,
  Routes,
  useLocation,
  useNavigationType
} from "react-router-dom"

export const initializeFaro = () => {
  const faro = coreInit({
    app: {
      name: "react-app",
      version: "1.0.0",
      environment: "development",
      release: "beta"
    },
    instrumentations: [
      ...getWebInstrumentations(),
      new TracingInstrumentation(),
      new ReactIntegration({
        router: {
          version: ReactRouterVersion.V6,
          dependencies: {
            createRoutesFromChildren,
            matchRoutes,
            Routes,
            useLocation,
            useNavigationType
          }
        }
      })
    ],
    transports: [
      new FetchTransport({
        url: "https://telemetry-collector.net/collect",
        apiKey: "secret"
      }),
      new ConsoleTransport()
    ]
  })

  faro.api.pushLog(["Faro was initialized"])

  return faro
}
```

#### Index.js
```javascript
import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./App";
import { FaroErrorBoundary, FaroProfiler } from "@grafana/faro-react";

import { initializeFaro } from "./faro";

initializeFaro();

ReactDOM.render(
  <React.StrictMode>
    <FaroErrorBoundary>
      <FaroProfiler>
        <App />
      </FaroProfiler>
    </FaroErrorBoundary>
  </React.StrictMode>,

  document.getElementById("root")
);
```

#### App.js
```javascript
import React from "react"
import { BrowserRouter as Router, Route } from "react-router-dom"
import "./App.css"
import {
  Dashboard,
  Health,
  EnvironmentVariables,
  About,
  Home,
  Todo
} from "./pages"
import { FaroRoutes } from "@grafana/faro-react"

function App() {
  return (
    <Router>
      <FaroRoutes>
        <Route exact path="/" element={<Home />} />
        <Route path="/about" element={<About />} />

        <Route path="/dashboard" element={<Dashboard />} />

        <Route path="/health" element={<Health />} />
        <Route
          path="/environment-variables"
          element={<EnvironmentVariables />}
        />
        <Route path="/todos" element={<Todo />} />
      </FaroRoutes>
    </Router>
  )
}

export default App
```

#### Fetch
```javascript
const customFetch = async (url, obj = {}) => {

  const response = await fetch(url, obj);

  return response;
};

export default customFetch;
```

**Comment by codecapitano** [comment]
Hi @therealmanny thanks a lot for opening the issue and the detailed description 🙏    

I have a question to double check if this is a similar issue as in #131 . 

You mentioned that you followed [this example](https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md#with-custom-opentelemetry-tracing-configuration). 

I can't see the full URL in the screenshots above but it may be that this issue is still CORS related (as in [issue 131](https://github.com/grafana/faro-web-sdk/issues/131#issuecomment-1470396714)).  In this case [the Open Telemetry XHR and Fetch instrumentations provide an option to configure (regex) which URLs should have a traceparent header added](https://github.com/open-telemetry/opentelemetry-js/blob/b8923d5165f4be66c974dacd5be1744670a3bb5d/experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts#L56).  

This config option is not available yet when using Faros `TracingInstrumentation()` out of-of-the-box config for the Otel Instruments. So you need to provide the instrumentations via config to `TracingInstrumentation` and configure `propagateTraceHeaderCorsUrls`.

  Example:  
  
```js
   const faro = initializeFaro({
  url: 'the-collector-url,
  apiKey: 'secret',
  instrumentations: [
	...getWebInstrumentations(), 
	new TracingInstrumentation({
  		new DocumentLoadInstrumentation(),
    		new FetchInstrumentation({ ignoreUrls,  propagateTraceHeaderCorsUrls: […]}),
    		new XMLHttpRequestInstrumentation({ ignoreUrls,  propagateTraceHeaderCorsUrls: […] }),
    		new UserInteractionInstrumentation(),
  	})
  ],
  app: {
    name: 'frontend',
    version: '1.0.0',
  },
});
```

  Can you do me a favor and test if this solves the issue?   
  
  Cheers,
   Marco

**Comment by therealmanny** [comment]
Hi, @codecapitano thanks for taking a look and responding to my issue. The issue I was experiencing was similar to issue #131. I did not read that issue carefully when I took a look at it. Your suggestion fixed my issue. Thanks again, and I appreciate you taking the time to respond.

```javascript
export const initializeFaro = () => {
  const faro = coreInit({
    app: {
      name: "react-app",
      version: "1.0.0",
      environment: "development",
      release: "beta"
    },
    instrumentations: [
      ...getWebInstrumentations(),
      new TracingInstrumentation({
        instrumentations: [
          new DocumentLoadInstrumentation(),
          new FetchInstrumentation({
            ignoreUrls: ["the-collector-url"],
            propagateTraceHeaderCorsUrls: [
              new RegExp("https://jsonplaceholder.typicode.com/*")
            ]
          }),
          new XMLHttpRequestInstrumentation({
            ignoreUrls: ["the-collector-url"],
            propagateTraceHeaderCorsUrls: [
              new RegExp("https://jsonplaceholder.typicode.com/*")
            ]
          }),
          new UserInteractionInstrumentation()
        ]
      }),
      new ReactIntegration({
        router: {
          version: ReactRouterVersion.V6,
          dependencies: {
            createRoutesFromChildren,
            matchRoutes,
            Routes,
            useLocation,
            useNavigationType
          }
        }
      })
    ],
    transports: [
      new FetchTransport({
        url: "the-collector-url",
        apiKey: "secret"
      }),
      new ConsoleTransport()
    ]
  });

  faro.api.pushLog(["Faro was initialized"]);

  return faro;
};
```
