### ISSUE TITLE
Track window dimensions

### ISSUE THREAD

**Issue by codecapitano** [grafana/faro-web-sdk#147]
## Description
Track the window size of the respective device

## Proposed solution
Get [`Window.innerHeight`](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight) and [`Window.innerWidth`](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth) and add the dimensions to the Browser Meta Object.

In the OlpHttpTransport the screen dimensions will be translated translated to 
[`browser.screen_width` and `browser.screen_height` as defined in Semantic conventions for browser events](https://github.com/scheler/opentelemetry-specification/blob/rum-events/specification/logs/events/semantic_conventions/browser.md#resourcevarying)

**Comment by eskirk** [comment]
@codecapitano did we get this done last quarter? need to move to Q3?

**Comment by codecapitano** [comment]
Still open

**Comment by codecapitano** [comment]
Thanks for bumping this @Starefossen.
It's a very low hanging fruit.
I think we'll release it with the next Faro version
