### ISSUE TITLE
Inject user details in event log.

### ISSUE THREAD

**Issue by AMontagu** [grafana/faro-web-sdk#181]
## Description

User details set by faro.api.setUser are injected in log of kind log and measurement but not in log of kind event.

## Proposed solution

Inject user details in the event log too to be able to have grafana dashboard displaying both log and event for an user filter

## Context

"@grafana/faro-web-sdk": "1.0.2",
"@grafana/faro-web-tracing": "1.0.2",

![Screenshot from 2023-05-04 11-20-44](https://user-images.githubusercontent.com/11883225/236163323-1d754e9a-b24e-453d-a752-219ab9c382a1.png)

**Comment by cedricziel** [comment]
Hi @AMontagu  - thanks for opening the ticket. I think this is a bug. All signals should share the same metas.

**Comment by codecapitano** [comment]
Hi @AMontagu 

I can not reproduce the issue. 

Setting an initial user and a user change by calling `setUser` both works.
The user data meta is sent with the event and it is discoverable in Loki as well. 

Request payload for the click event:
<img width="1265" alt="image" src="https://github.com/grafana/faro-web-sdk/assets/47627413/e5a34df5-6272-4240-81fe-f911762d653d">


User data in Loki:
<img width="2151" alt="image" src="https://github.com/grafana/faro-web-sdk/assets/47627413/1f7c4a15-f617-4736-bdbb-a5d9122f2bc2">

I used our demo app too test the following scenarios:
* Set a static user in initialize
* Set a static user in  initialize and change user later
* Don't set a user in initialize and use `setUser` to set it later

Can you provide more information e. g. on how you set the user?

Cheers,
Marco

**Comment by codecapitano** [comment]
@AMontagu any updates here or can we close the issue?

**Comment by AMontagu** [comment]
@codecapitano I think you can close it.

I think the two event I receive session_start and view_changed are the one from the page load ans the user is not still set.

What make me wrong is that when I am navigating in different page after the user is set there is no other event that is trigger. I mingled the first event with an user event. Do you know if Vue router navigation (that use the browser history api) trigger navigation event ?

**Comment by codecapitano** [comment]
> I think the two event I receive session_start and view_changed are the one from the page load ans the user is not still set.


* The `session_start` event is fired when initializing the [SessionInstrumentation](https://github.com/grafana/faro-web-sdk/blob/5b3df310b91646648c135a258d8e670909b4985f/packages/web-sdk/src/instrumentations/session/instrumentation.ts#L19-L20)

* The  `view_changed` event is fired when initializing the [ViewInstrumentation](https://github.com/grafana/faro-web-sdk/blob/5b3df310b91646648c135a258d8e670909b4985f/packages/web-sdk/src/instrumentations/view/instrumentation.ts#L18)
