### ISSUE TITLE
Faro quick start: Confusing use of port 12345

### ISSUE THREAD

**Issue by DazWilkin** [grafana/faro-web-sdk#196]
## Description

I'm new to Grafana Faro but familiar with Grafana and Prometheus. I'm struggling to work through the tutorial.

One confusion is understanding the Grafana Agent configuration and the use of `server.port` value 12345. This appear to cause a bind conflict when running the Agent's container image.

If `gettingstarted.agent.yaml` corresponds to the config in the [Get started with Grafana Faro Web SDK](https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md)

```bash
podman run \
--interactive --tty --rm \
--publish=8888:8888/tcp \
--publish=12345:12345/tcp \
--publish=12346:12346/tcp \
--volume=${PWD}/tmp/agent:/etc/agent/data \
--volume=${PWD}/gettingstarted.agent.yaml:/etc/agent/agent.yaml \
docker.io/grafana/agent:v0.33.2 \
  --config.file=/etc/agent/agent.yaml \
  --enable-features=integrations-next
```
The Agent appears (!?) to start with `12345` (HTTP) and `12346` (gRPC) preconfigured through the default `--server.http.address="0.0.0.0:12345"` configuration.
```
ts=2023-05-19T16:32:01.126467952Z caller=server.go:191 level=info msg="server listening on addresses" http=127.0.0.1:12345 grpc=127.0.0.1:12346 http_tls_enabled=false grpc_tls_enabled=false
```
However, this conflicts with the attempt to configure `app_agent_receiver_configs`'s `server.port` to the same value in the config.
```
ts=2023-05-19T16:32:01.131255413Z caller=app_agent_receiver.go:170 level=info component=integrations integration=app_agent_receiver instance=frontend msg="starting app agent receiver" host=0.0.0.0 port=12345
ts=2023-05-19T16:32:01.131480888Z caller=workers.go:119 level=error component=integrations msg="integration exited with error" id=app_agent_receiver/frontend err="listen tcp 0.0.0.0:12345: bind: address already in use"
ts=2023-05-19T16:32:01.133530022Z caller=app_agent_receiver.go:170 level=info component=integrations integration=app_agent_receiver instance=frontend msg="starting app agent receiver" host=0.0.0.0 port=12345
ts=2023-05-19T16:32:01.133620472Z caller=workers.go:119 level=error component=integrations msg="integration exited with error" id=app_agent_receiver/frontend err="listen tcp 0.0.0.0:12345: bind: address already in use"
```

## Steps to reproduce

Run the Grafana Agent per the above `podman run` with the current Agent config in [Get started with Grafana Faro Web SDK](https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md)

## Expected behavior

No errors.

## Actual behavior

See explanation above.

## Environment

- **SDK version:** v0.332
- **SDK instrumentations:**
- **Device type:**
- **Device name:**
- **OS:** Ubuntu Linux 22.04.2
- **Browser:** N/A

**Comment by DazWilkin** [comment]
My solution is to use an available port (e.g. `8888`):

`working.agent.yaml`:
```YAML
integrations:
  app_agent_receiver_configs:
  -  autoscrape:
       enable: true
       metrics_instance: default
     instance: frontend
     server:
       host: 0.0.0.0
       port: 8888
       api_key: secret
       cors_allowed_origins:
       - "http://localhost:8080"
```
Then expose this config, this port and reconfigure the Agent to use `0.0.0.0` rather than `127.0.0.1`:

```bash
podman run \
--interactive --tty --rm \
--publish=8888:8888/tcp \
--publish=12345:12345/tcp \
--publish=12346:12346/tcp \
--volume=${PWD}/tmp/agent:/etc/agent/data \
--volume=${PWD}/working.agent.yaml:/etc/agent/agent.yaml \
docker.io/grafana/agent:v0.33.2 \
  --config.file=/etc/agent/agent.yaml \
  --enable-features=integrations-next \
  --server.http.address=0.0.0.0:12345
```
And then, from the JavaScript client:

`index.js`:
```JavaScript
const faro = initializeFaro({
  transports: [
    new FetchTransport({
      url: "http://localhost:8888/collect",
      apiKey: "secret",  
    }),
  ],
  app: {
    name: 'frontend',
    version: '1.0.0',
  },
});

```

**Comment by nikmish1** [comment]
I tried the same but getting following error on frontend

index.tsx:16 Faro
 @grafana/faro-web-sdk:transport-fetch
 Failed sending payload to the receiver
 {meta: {…}, events: Array(1), logs: Array(1)} MirageError {description: 'Mirage: undefined', fileName: undefined, lineNumber: undefined, message: "Mirage: Your app tried to POST 'http://127.0.0.1:8… a namespace? The existing namespace is undefined", name: 'Error', …}description: "Mirage: undefined"fileName: undefinedlineNumber: undefinedmessage: "Mirage: Your app tried to POST 'http://127.0.0.1:8888/collect', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace? The existing namespace is undefined"name: "Error"number: undefinedstack: "Mirage: Error: Your app tried to POST 'http://127.0.0.1:8888/collect', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace? The existing namespace is undefined\n    at new MirageError (http://localhost:3001/static/js/bundle.js:48033:13)\n    at assert (http://localhost:3001/static/js/bundle.js:48019:11)\n    at Pretender.unhandledRequest (http://localhost:3001/static/js/bundle.js:54038:13)\n    at Pretender.handleRequest (http://localhost:3001/static/js/bundle.js:56716:14)\n    at FakeRequest.send (http://localhost:3001/static/js/bundle.js:56513:21)\n    at http://localhost:3001/static/js/bundle.js:56395:9\n    at new Promise (<anonymous>)\n    at fetch (http://localhost:3001/static/js/bundle.js:56321:10)\n    at http://localhost:3001/static/js/bundle.js:7356:18\n    at work (http://localhost:3001/static/js/bundle.js:3824:7)"[[Prototype]]: Error
internalLogger.error @ createInternalLogger.ts:18
logError @ baseExtension.ts:30
(anonymous) @ transport.ts:99
Promise.catch
(anonymous) @ transport.ts:97
work @ promiseBuffer.ts:34
(anonymous) @ promiseBuffer.ts:64
add @ promiseBuffer.ts:58
(anonymous) @ transport.ts:55
(anonymous) @ transport.ts:16
__webpack_modules__../node_modules/@grafana/faro-web-sdk/dist/esm/transports/fetch/transport.js.__awaiter @ transport.ts:16
send @ transport.ts:47
batchedSend @ initialize.ts:81
flush @ batchExecutor.ts:84
(anonymous) @ batchExecutor.ts:52
setInterval
start @ batchExecutor.ts:52
BatchExecutor @ batchExecutor.ts:25
initializeTransports @ initialize.ts:111
initializeFaro @ initialize.ts:27
initializeFaro @ initialize.ts:14
./src/index.tsx @ index.tsx:16
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
index.tsx:16 Faro
 @grafana/faro-web-sdk:transport-fetch
 Failed sending payload to the receiver
 {meta: {…}, measurements: Array(2), events: Array(1)} MirageError {description: 'Mirage: undefined', fileName: undefined, lineNumber: undefined, message: "Mirage: Your app tried to POST 'http://127.0.0.1:8… a namespace? The existing namespace is undefined", name: 'Error', …}
internalLogger.error @ createInternalLogger.ts:18
logError @ baseExtension.ts:30
(anonymous) @ transport.ts:99
Promise.catch
(anonymous) @ transport.ts:97
work @ promiseBuffer.ts:34
(anonymous) @ promiseBuffer.ts:64
add @ promiseBuffer.ts:58
(anonymous) @ transport.ts:55
(anonymous) @ transport.ts:16
__webpack_modules__../node_modules/@grafana/faro-web-sdk/dist/esm/transports/fetch/transport.js.__awaiter @ transport.ts:16
send @ transport.ts:47
batchedSend @ initialize.ts:81
flush @ batchExecutor.ts:84
(anonymous) @ batchExecutor.ts:52
setInterval
start @ batchExecutor.ts:52
BatchExecutor @ batchExecutor.ts:25
initializeTransports @ initialize.ts:111
initializeFaro @ initialize.ts:27
initializeFaro @ initialize.ts:14
./src/index.tsx @ index.tsx:16
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
localhost/:1 Unchecked runtime.lastError: The message port closed before a response was received.
