### ISSUE TITLE
Task buffer full

### ISSUE THREAD

**Issue by cupcakearmy** [grafana/faro-web-sdk#197]
## Description

In localhost deployments, sometimes, the Faro SDK produces lots of the same error. Easily around 100, saying that the `Task buffer full`. Our localhost is enabled in the cors settings, and sometimes it works, sometimes not.

Any idea why / hint to what we might be doing wrong?

Things tried:

- Clear the complete data (cache, webstorage, etc.) for the domain (localhost).

## Steps to reproduce

Our setup is:

```
initializeFaro({
    url: 'https://faro-collector-prod-eu-west-0.grafana.net/collect/***',
    app: {
        name: '***',
        version: '***',
        environment: '***',
    },
});
```

## Environment

- **SDK version:** 1.0.5
- **SDK instrumentations:** Default settings, see above
- **Device type:**
- **Device name:**
- **OS:** macOS
- **Browser:** Chrome, Firefox

## Demo

![Screenshot 2023-05-22 at 11 28 01](https://github.com/grafana/faro-web-sdk/assets/14948823/4c5de807-cb80-4140-b7cf-431c3d8b7947)

**Comment by codecapitano** [comment]
Hey @cupcakearmy thanks for the report.

To help you better, would you mind telling us:
* what instrumentations you have enabled?
* Did you disable the [dedupe](https://github.com/grafana/faro-web-sdk/blob/e38fdf19eded319580991a8b08d4950918f52da3/packages/core/README.md#L27) option or maybe enable [skipDedupe](https://github.com/grafana/faro-web-sdk/blob/e38fdf19eded319580991a8b08d4950918f52da3/packages/core/README.md#L118) for errors?
* What transports do you use

You can just post your init code and remove the bits not meant for public. This would make things a bit easier.

**Note:**
The request buffer size can be changed with the [bufferSize](https://github.com/grafana/faro-web-sdk/blob/e38fdf19eded319580991a8b08d4950918f52da3/packages/web-sdk/src/transports/fetch/types.ts#L12) property in `FetchTransport` (default value is 30).

Cheers,
Marco

**Comment by cupcakearmy** [comment]
Hey, thanks for the quick reply!

The instrumentations are the default ones. The init code is above :)

The dedupe options does not seem to have an effect. However it might be a thing on our side, since the error occurs only with the dev server, and not in the bundled builds.

The skipDedupe flag I did not try, as it's only available for custom fired events afai could grasp from the docs.

Increasing the buffer size to `1_000` seems to fix the issue, however it's still werid that this only occurs in the dev server.

```typescript
 initializeFaro({
    transports: [new FetchTransport({
        url: 'https://faro-collector-prod-eu-west-0.grafana.net/collect/***',
        bufferSize: 1_000
    })],
    app: {
        // ...
    },
});
```

**Comment by codecapitano** [comment]
@cupcakearmy thank you too for your fast reply :)

Ah ok that's all init code. Just wanted to be sure that we do not miss anything.

> The dedupe options does not seem to have an effect.
Maybe there is still a tiny difference in the error data. 
With the `dedupe` option enabled (which is the default) the error api diffs the errors `type`, `stack trace` and `value`.

> Increasing the buffer size to 1_000 seems to fix the issue, however it's still werid that this only occurs in the dev server.
Yes this is not an ideal solution.
But I have a good message here, we are currently working on implementing Signal batching which very likely will solve the issue. A [draft PR to add batching](https://github.com/grafana/faro-web-sdk/pull/185) is already open so you can follow the progress if you are interested. 

Cheers,
Marco

**Comment by codecapitano** [comment]
@cupcakearmy A colleague mentioned the following which may cause this behavior.

> Another point of failure may be the server not responding to requests, requests taking way too much time due to payload size or other issues.

**Comment by cupcakearmy** [comment]
@codecapitano For now I've simply disabled Faro in dev builds, which we don't really need anyways. The server is a paid grafana endpoint, so i'd immagine that should (hopefully) not be the bottleneck xD

My suspicion is that with the dev server, somehow, there are too many events happening that faro wants to collect, but our build system is also not the newest, so it might be on our side :)

**Comment by codecapitano** [comment]
@cupcakearmy can we close the issue for now?
