### ISSUE TITLE
TypeError: initializeFaro is not a function

### ISSUE THREAD

**Issue by bodecci** [grafana/faro-web-sdk#198]
using basic configuration:

```
import  initializeFaro  from "@grafana/faro-web-sdk";
...

const faro = initializeFaro({
  url: "http://localhost:5050/collect",
  apiKey: "secret",
  app: {
    name: "Salary Calc",
    version: "1.0.0",
  },
});
```
getting `TypeError: initializeFaro is not a function` when running in app.js

    SDK version: faro-web-sdk": "^1.0.5"
    SDK instrumentations: Default settings, see above
    Device type: MBP
    Device name:
    OS: macOS M1
    Browser: Firefox

**Comment by eskirk** [comment]
Hi @bodecci - at first glance this could be happening since your `initializeFaro` import does not have curly braces. 

Can you try import like this:
```js
import { initializeFaro } from "@grafana/faro-web-sdk";
```

Just to make sure that nothing else is the problem. Let me know, thanks.

**Comment by bodecci** [comment]
> Hi @bodecci - at first glance this could be happening since your `initializeFaro` import does not have curly braces.
> 
> Can you try import like this:
> 
> ```
> import { initializeFaro } from "@grafana/faro-web-sdk";
> ```
> 
> Just to make sure that nothing else is the problem. Let me know, thanks.

using the { } actually throws an error: `SyntaxError: The requested module '...@grafana/faro-web-sdk/dist/cjs/index.js' does not provide an export named 'initializeFaro' `. 
I was able to solve the error. Not using the curly braces worked and moving where I declared and used faro solved it.

Thanks for the quick response.
