### ISSUE TITLE
Importing faro-web-tracing package is breaking the Vue js application using Vuex

### ISSUE THREAD

**Issue by sudalaimuthu-a** [grafana/faro-web-sdk#201]
## Description

When i'm import grafana faro "grafana/faro-web-tracing" package it breaking the application giving error.
Unhandled Promise rejection: Cannot read properties of undefined (reading '__esModule') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading '__esModule')

## Steps to reproduce

1. Add  faro-web-tracing to the application  using 

> 1.     "vue": "2.6.14",
> 2.     "vue-router": "3.5.2",
> 3.     "vuex": "3.6.2",
> 4.     "vuex-persistedstate": "4.1.0" 

2.  import { TracingInstrumentation } from '@grafana/faro-web-tracing';
3. Sample vuex commit, dispatch, action , etc
4. Now call an api and update the vue store 

## Expected behavior

Api need to get called and should return the data

## Actual behavior

Api call is not even getting triggered, getting Unhandled Promise rejection: Cannot read properties of undefined or some time maximum call stack exceeds

## Environment

- **SDK version:** 1.0.5
- **SDK instrumentations:** Web SDK, Web Tracing, Vuejs
- **Device type:** desktop
- **Device name:** MacBook Pro
- **OS:** macOS Ventura 13.3.1 (a) 
- **Browser:** Chrome Version 112.0.5615.137 (Official Build) (arm64)

**Comment by codecapitano** [comment]
Hi @sudalaimuthu-a and thanks for the report. 

Would you mind sharing your init code for the web-sdk?
This would help us to reproduce the issue.

Thanks in advance, cheers
Marco

**Comment by sudalaimuthu-a** [comment]
@codecapitano , as its an internal application I can't share the code here.

I found the code which is creating the issue and address this issue by replace zoneContextManager with StackContextManager
//import { ZoneContextManager } from "@opentelemetry/context-zone";
import { WebTracerProvider, StackContextManager } from "@opentelemetry/sdk-trace-web";

By doing so I remove the dependency of zone.js

**Comment by codecapitano** [comment]
Hey @sudalaimuthu-a thnaks so much! 
Glad you found a way to solve the problem.

Can the issue be closed then?

Cheers,
Marco
