### ISSUE TITLE
Remove UserInteractionInstrumentation from quickstart

### ISSUE THREAD

**Issue by AMontagu** [grafana/faro-web-sdk#222]
## Description

Since version 1.1.1 UserInteractionInstrumentation is not integrated by default in grafana faro but still used in quickstart part: "With custom OpenTelemetry tracing configuration"

Either add a step to specify extra package from OTEL that can be imported or remove le line concerned.

If you confirm what solution you recommend I can make the PR event if it's only 2 line change.

**Comment by codecapitano** [comment]
Hi @AMontagu 

Oh this is a leftover so we should remove it from the quickstart docs.
Would be awesome if you tackle this. 

Thanks so much in advance. Cheers,
Marco

**Comment by codecapitano** [comment]
Hi @AMontagu 

Oh this is a leftover so we should remove it from the quickstart docs.
Would be awesome if you tackle this. 

Thanks so much in advance. Cheers,
Marco
