### ISSUE TITLE
Others platforms

### ISSUE THREAD

**Issue by GuiHS01** [grafana/faro-web-sdk#232]
Any plans to make a _faro-web-sdk_ for Flutter?

**Comment by codecapitano** [comment]
Hi @GuiHS01 currently our focus is on the web. instrumentation. And we have yet no plans midterm to support other platforms.

I know there is a [project started by an individual contributor to make Faro support flutter](https://github.com/cedricziel/flutter_faro). Maybe this is interesting for you.

/cc @cedricziel
