### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by mk48** [grafana/faro-web-sdk#233]
## Description

Getting window is not defined error
![image](https://github.com/grafana/faro-web-sdk/assets/3082469/1a13721c-c38b-438c-a3f4-361d1dc00b51)

## Steps to reproduce

1. Create NextJs-12 application with app directory.
2. Use below initialization
```
import {
  ConsoleInstrumentation,
  ConsoleTransport,
  ErrorsInstrumentation,
  FetchTransport,
  initializeFaro,
  LogLevel,
  SessionInstrumentation,
  WebVitalsInstrumentation,
} from "@grafana/faro-web-sdk";
import { TracingInstrumentation } from "@grafana/faro-web-tracing";
import type { Faro } from "@grafana/faro-core";

const faro = initializeFaro({
  // Mandatory, the URL of the Grafana Cloud collector with embedded application key.
  // Copy from the configuration page of your application in Grafana.
  url: "http://agent-collector-url:3900/collect",

  // Mandatory, the identification label(s) of your application
  app: {
    name: "app-name",
    version: "2.0.0", // Optional, but recommended
  },

  instrumentations: [new ErrorsInstrumentation(), new WebVitalsInstrumentation(), new SessionInstrumentation()],
});

export default faro;

```

## Expected behavior
Should run without not defined error.

## Environment

- @grafana/faro-web-sdk: "^1.1.2"
- @grafana/faro-web-tracing: "^1.1.2"
- @grafana/faro-react: "^1.1.2"
- Device type: desktop
- OS: Windows 10
- Browser: FireFox 102.13.0esr (64-bit)

**Comment by AyanBhadury** [comment]
Hi, this is because next app uses server side rendering you need to disable SSR for the component where faro is configured, since faro needs a window or a browser object to render.

You can refer to this demo project for reference - https://github.com/AyanBhadury/faro-next-app

**Comment by mk48** [comment]
@AyanBhadury  Thanks for the reply, 
How about "use client"; option in app folder. That will not be SSR.
I have created simple Next-App codesandbox with "use client" option and copy pasted your Grafana-Faro lines.

Could you please have a look into this?
https://codesandbox.io/p/sandbox/reverent-brook-xv577v

![image](https://github.com/grafana/faro-web-sdk/assets/3082469/b9dffded-8297-4175-aa68-0c42634291f9)

**Comment by angel1254mc** [comment]
Hi @mk48! Based on the [next13 docs](https://nextjs.org/docs/getting-started/react-essentials#client-components), even though components that use the "use client" directive are hydrated on the client, they can still get pre-rendered on the server

> Client Components enable you to add client-side interactivity to your application. In Next.js, they are [pre-rendered](https://nextjs.org/docs/app/building-your-application/rendering#component-level-client-and-server-rendering) on the server and [hydrated](https://nextjs.org/docs/app/building-your-application/rendering#component-level-client-and-server-rendering) on the client.

You could try initializing faro in the useEffect of a client component, this should work since these run on the client on first render. You could either turn the RootLayout into a client component, or have a React.Context that wraps around the rest of your application. Here's an example initializing it on the root of your app w/ "use client" directive. 
```jsx
"use client"
import { useEffect, useRef } from 'react';
import { initializeFaro } from "@grafana/faro-web-sdk";

export default function RootLayout({ children }) {  
  const faroRef = useRef(null);  
  
  useEffect(() => {
    if (!faroRef.current) {
      faroRef.current = initializeFaro({...})
    }
  }, [])

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}

```
Let me know if this works for you!

**Comment by mk48** [comment]
Thanks @angel1254mc It worked 🎇

**Comment by MarcioJales** [comment]
I had a similar issue and solved by using the `useEffect` hook, as suggested by [NextJS documentation](https://nextjs.org/docs/pages/building-your-application/rendering/client-side-rendering)
