### ISSUE TITLE
Demo doesn't work anymore with latest grafana agent (0.35.0)

### ISSUE THREAD

**Issue by mxab** [grafana/faro-web-sdk#234]
## Description

Since the release of grafana agent 0.35. The agent doesn't start anymore. The agent logs print the following:

```
msg="error creating the agent server entrypoint" err="failed to construct app_agent_receiver integration \"@grafana/faro-demo\": push receiver factory not found for traces instance \"@grafana/faro-demo\""
```

## Steps to reproduce

```
docker compose pull
docker compose up
```

**Comment by codecapitano** [comment]
Hi @mxab thanks for reporting the issue.

In this case it seem to be related to an agent upgrade.
We opened an [issue in Grafana Agent repository](https://github.com/grafana/agent/issues/4632).

Cheers,
Marco

**Comment by mxab** [comment]
Looks good, thanks!
