### ISSUE TITLE
how should i use faro-web-sdk with react-route-dom v5? and route-change event not work,now

### ISSUE THREAD

**Issue by Jackierchan** [grafana/faro-web-sdk#251]
## Environment

- **SDK version:**
- **SDK instrumentations:**
- **Device type:**
- **Device name:**
- **OS:**
- **Browser:**

**Comment by codecapitano** [comment]
Hi @Jackierchan 

Would you please provide us with more information as per our template?
This makes it easier for us to reproduce and narrow down problems.

Cheers,
Marco
