### ISSUE TITLE
OltpHttpTransport Resulting in 400 Response Status 

### ISSUE THREAD

**Issue by bdschaap** [grafana/faro-web-sdk#252]
I'm trying a simple Hello World type app that's instrumented w/ Faro Web SDK.  I'm using the experimental OtlpHttpTransport package to send telemetry to an OpenTelemetry Collector endpoint.  However, I received a 400 error with this message.
`{"code":3,"message":"ReadObjectCB: expect { or n, but found [, error found in #1 byte of ...|[{\"resource|..., bigger context ...|[{\"resource\":{\"attributes\":[{\"key\":\"browser.mobile\"|..."}`
I checked the request and it's sending this as the payload.
`[{"resource":{"attributes":[{"key":"browser...`
The payload should look like this per the Otel spec -
`{"resourceLogs":[{"resource":{"attributes":[{"key":"browser...`
Is this a bug or am I using it incorrectly?

**Comment by codecapitano** [comment]
Hi @bdschaap thank you reporting. 
Would you telling me the `SDK version` and what `instrumentations` you use?

Cheers,
Marco

**Comment by bdschaap** [comment]
Thanks for confirming.  I was using v1.1.3 of faro-transport-otlp-http with a variety of instrumentations (ErrorsInstrumentation, WebVitalsInstrumentation, TracingInstrumentation, ConsoleInstrumentation, SessionInstrumentation).

**Comment by codecapitano** [comment]
Thank you so much @bdschaap  this finding was very valuable! 

We found the issue and the fix is in review.

Cheers,
Marco

**Comment by bdschaap** [comment]
@codecapitano I tried out the code in the PR and was able to successfully send logs an traces to my Otel Collector.  Much appreciated.  Do you know approximately when the PR will be approved and a new release is available?

**Comment by codecapitano** [comment]
Wow @bdschaap thanks so much for testing the change ❤️ 

I would fix another issue today and release both changes/fixes together. So I am aiming for a patch release on Monday.
