### ISSUE TITLE
Web vitals events trigger 400 error

### ISSUE THREAD

**Issue by NickAkhmetov** [grafana/faro-web-sdk#269]
## Description

Sending web vitals events from our react application results in a `json: cannot unmarshal number into Go struct field Event.events.attributes of type string` error being thrown. The error message makes up the entirety of the response body. All other tracked events/errors are successfully tracked.

## Steps to reproduce

<details><summary>Faro Initialization config</summary>
<p>

Faro is initialized by calling this function before the application is mounted: https://github.com/hubmapconsortium/portal-ui/blob/main/context/app/static/js/helpers/init-trackers.js#L9

</p>
</details> 

<details><summary>Request Body</summary>
<p>

```
{
  "meta": {
    "session": { "id": "aQZBsjico7" },
    "sdk": {
      "name": "@grafana/faro-core",
      "version": "1.2.1",
      "integrations": [
        {
          "name": "@grafana/faro-web-sdk:instrumentation-errors",
          "version": "1.2.1"
        },
        {
          "name": "@grafana/faro-web-sdk:instrumentation-web-vitals",
          "version": "1.2.1"
        },
        {
          "name": "@grafana/faro-web-sdk:instrumentation-session",
          "version": "1.2.1"
        },
        {
          "name": "@grafana/faro-web-sdk:instrumentation-view",
          "version": "1.2.1"
        },
        {
          "name": "@grafana/faro-web-sdk:instrumentation-console",
          "version": "1.2.1"
        },
        { "name": "@grafana/faro-web-tracing", "version": "1.2.1" },
        { "name": "@grafana/faro-react", "version": "1.2.1" }
      ]
    },
    "app": {
      "name": "hubmap-data-portal",
      "version": "portal-ui-react@0.79.4",
      "environment": "local"
    },
    "view": { "name": "default" },
    "browser": {
      "name": "Firefox",
      "version": "117.0",
      "os": "Windows 10",
      "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0",
      "language": "en-US",
      "mobile": false,
      "brands": "unknown"
    },
    "page": { "url": "http://localhost:5001/search?entity_type[0]=Dataset" }
  },
  "measurements": [
    {
      "type": "web-vitals",
      "values": { "ttfb": 2097 },
      "timestamp": "2023-09-21T15:51:59.192Z",
      "context": {}
    }
  ],
  "events": [
    {
      "name": "Web Vitals",
      "domain": "browser",
      "attributes": {
        "category": "Web Vitals",
        "action": "TTFB",
        "label": "v3-1695311518656-3919272166935",
        "value": 2097,
        "nonInteraction": true
      },
      "timestamp": "2023-09-21T15:51:59.194Z"
    }
  ]
}


```

</p>
</details> 

## Expected behavior

A 202 successful response, web vitals being successfully recorded

## Actual behavior

A 400 error, web vitals not successfully recording

## Environment

- **SDK version:** 1.2.0, 1.2.1
- **SDK instrumentations:** Errors, Web-Vitals, Session, View, Console, faro-web-tracing, faro-react
- **Device type:** Desktop
- **Device name:** N/A, custom built
- **OS:** Windows 11
- **Browser:** Firefox 117.0.1, reproduced with Edge 117.0.2045.31

## Demo

Recorded in staging environment:

https://github.com/grafana/faro-web-sdk/assets/19957804/0bee952d-e260-4ed3-a61c-d2ba68dbc491

## Context

[HuBMAP Data Portal Homepage](https://portal.hubmapconsortium.org/)

**Comment by eskirk** [comment]
Hi @NickAkhmetov thank you for the report. Please link your homepage when you get the chance, I will investigate this today.

**Comment by NickAkhmetov** [comment]
@eskirk Thanks for the prompt follow-up! I've linked the homepage in the link above.

**Comment by codecapitano** [comment]
Hey @NickAkhmetov 

Just followed the link you posted above to inspect the error.
I think I know what causes the 404.

It look like you track TTFB manually and send it via the event API (`pushEvent(...)`). Is this correct?

When looking at the event attributes the value for TTFB is provided as a number. 
But [Faro defines that all attributes need to be of type string](https://github.com/grafana/faro-web-sdk/blob/2e362fe0c15b4118abd25f08d67be6e063e25cfd/packages/core/src/api/events/types.ts#L10). So also the receiver expects the attributes to be of type string thus responding with a 400. 

This is also what the error message is saying:
`json: cannot unmarshal number into Go struct field Event.events.attributes of type string`

So, if you add numbers to the event.attributes object you need to convert them to a string before sending them.

Cheers,
Marco

**Comment by NickAkhmetov** [comment]
@codecapitano Thanks for taking a look! That seems to be an accurate diagnosis - our legacy web vitals tracking uses GA, which required these values to be integers; during the migration, we updated our `trackEvent` helper to also send everything to Faro, but hadn't modified that piece of the logic. This clarifies our next steps greatly and clarifies the error message. Thank you very much!

For future cases/as a general enhancement, would it be possible to provide a more helpful error message?

**Comment by codecapitano** [comment]
Hey @NickAkhmetov 

> For future cases/as a general enhancement, would it be possible to provide a more helpful error message?
Oh yes, makes a lot of sense! Would you do me a favor and open an issue for it?

Cheers,
Marco

**Comment by codecapitano** [comment]
Thanks so much @NickAkhmetov for opening the feature request (#348)

Can we close this issue?   

Cheers,
Marco

**Comment by NickAkhmetov** [comment]
Absolutely! I wasn't sure what your team's preferred practice is 👍🏻 Closing the issue, thanks again for tracking down the cause!
