### ISSUE TITLE
Errors are not sent to grafana 

### ISSUE THREAD

**Issue by uabdullayev** [grafana/faro-web-sdk#362]
## Description

I see several errors which are not logged to grafana instance but they are logged to the console. For some reason the errors are originating from the instrumentation script in the faro sdk (see screenshot)

Also occasionally Faro fails to send payload with performance entries. 

## Steps to reproduce

The setup:

```
//global faro instance  
initialize() {
    initializeFaro({
      url: this.url,
      app: {
        name: this.appName,
        version: this.version,
        environment: this.environment,
      },
      isolate : true,
      beforeSend: (event) => {
        if ((event.meta.page.url.includes('aw'))) {
          return null;
        }
        return event;
      },
      instrumentations: [
        ...getWebInstrumentations(this.instrumentationsOptions),
        new TracingInstrumentation({
          instrumentationOptions: {
            propagateTraceHeaderCorsUrls: this.propagateTraceHeaderCorsUrls,
          },
        }),
        new PerformanceTimelineInstrumentation({
          beforeEmit: (performanceEntryJSON) => {
            const entryType = performanceEntryJSON.type;
            const type = performanceEntryJSON.type;

            if (entryType === 'navigation' && ['reload', 'back_forward'].includes(type)) {
              return false;
            }

            return performanceEntryJSON;
          },
        }),
      ],
    });
    window.globalFaro = faro;
  }
}
```

```
//micro front end set up:
 initialize() {
    initializeFaro({
      url: this.url,
      app: {
        name: this.appName,
        version: this.version,
        environment: this.environment,
      },
      isolate: true,
      beforeSend: (event) => {
        if (!(event.meta.page.url.includes('aw'))) {
          return null;
        }
        return event;
      },
    });
    window.awFaro = faro;
  }
```

## Environment

- **SDK version:**  1.2.1
- **SDK instrumentations:** Tracing Instrumentation, Performance Timeline Instrumentation
- **OS:** MACOS
- **Browser:** Chrome 118.0.5993.117

## Demo

<img width="1026" alt="Screenshot 2023-10-31 at 14 14 52" src="https://github.com/grafana/faro-web-sdk/assets/122971553/6bd9c169-0c65-44af-a773-9c9785661072">
<img width="1163" alt="Screenshot 2023-10-29 at 17 20 01" src="https://github.com/grafana/faro-web-sdk/assets/122971553/45ab4da1-0ddb-4c1a-a54c-92426f06a1f9">
<img width="1158" alt="Screenshot 2023-10-29 at 17 19 37" src="https://github.com/grafana/faro-web-sdk/assets/122971553/eb25eac8-7378-4a89-a804-93c25b9783ae">

**Comment by codecapitano** [comment]
Hi @uabdullayev 
It seems the beacon requests failed because of a CORS issue.

This [message is logged to the console by the FetchTransport](https://github.com/grafana/faro-web-sdk/blob/0af17fa4ad67f0460366441399ca46ffeb75ed3d/packages/web-sdk/src/transports/fetch/transport.ts#L72) but the error itself is not originating from it.

Did you double the CORS settings? 

Cheers,
Marco

**Comment by codecapitano** [comment]
Seems to work since we didn't here anything back and and have no other reports of the issue.
Closing this one for now.
