### ISSUE TITLE
Session Attributes are not being sent

### ISSUE THREAD

**Issue by log1NVolcom** [grafana/faro-web-sdk#371]
Session Attributes are not being sent, it seems when it creates a new session it doesn't get the configuration to use it

![image](https://github.com/grafana/faro-web-sdk/assets/13321520/fa078671-219e-4f48-9c9b-a35c684bf984)
## Steps to reproduce

1. Install faro sdk >=1.2.2
3. initializeFaro
```ts
initializeFaro({
                url: `url`,
                app: {
                    name: 'name',
                    environment: "production",
                },
                instrumentations: [
                    ...getWebInstrumentations(),
                ],
                session: createSession({
                    country: "EU",
                }),
});

```

## Expected behavior

The getSession() should have the attributes and session id that are in the configuration 

## Actual behavior

The getSession() doesn't get the attributes and session id that are in the configuration 

## Environment

- **SDK version:** >= 1.2.2
- **SDK instrumentations:** Web SDK,
- **Device type:** All
- **Device name:** All
- **OS:** All
- **Browser:** All

**Comment by codecapitano** [comment]
Thanks for reporting @log1NVolcom.
We've found the issue.

Cheers,
Marco

**Comment by codecapitano** [comment]
@log1NVolcom we released a new version which contains the fix. 
Can you confirm that the issue is solved?

Thanks,
Marco

**Comment by log1NVolcom** [comment]
@codecapitano I confim is working with the new release. 🚀 
Thank you!

**Comment by codecapitano** [comment]
Awesome @log1NVolcom  thanks a lot for opening the issue and for testing the fix 🙏
