### ISSUE TITLE
x-faro-session not compatible with grafana agent

### ISSUE THREAD

**Issue by Starefossen** [grafana/faro-web-sdk#386]
## Description

The recent change with adding x-faro-session is not supported by Grafana Agent which fails all CORS preflight requests with latest version of the Grafana Faro SDK. Grafana Agent only allows `content-type` for allowed headers and this is not configurable: ref. https://github.com/grafana/agent/blob/f1871dfd2a0acf5832d5f9d4aa155be34705b529/component/faro/receiver/handler.go#L72 

## Steps to reproduce

* Run latest version of Grafana Agent
* Run latest version of Grafana Faro SDK

https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md

## Expected behavior

It should be able to receive Grafana Faro telemetry.

## Actual behavior

It does not.

![image (2)](https://github.com/grafana/faro-web-sdk/assets/968267/581dcf70-1c50-4044-b3b5-b6825792ad1e)

## Environment

- **SDK version:** v1.2.8
- **SDK instrumentations:** Web SDK, Web Tracing, React
- **Device type:** desktop, tablet, mobile
- **Device name:** MacBook Pro 13", iPhone 6, Samsung Galaxy S20
- **OS:** macOS Ventura, iOS
- **Browser:** Chrome 106, Safari 11

## Context

Related to #377 #381 #374

**Comment by cedricziel** [comment]
PR'ed a change to the agent: https://github.com/grafana/agent/pull/5835

**Comment by cedricziel** [comment]
Pending a new agent version.
