### ISSUE TITLE
Navigation timings and resource timings should have a causal relation

### ISSUE THREAD

**Issue by cedricziel** [grafana/faro-web-sdk#388]
## Description

In order to understand which specific resources with which specific timings were loaded as part of a page-load, there should be an identifier that can be used to find all the resource timings that are associated with a navigation timing.

Example:
- navigation-timing: page-load-a (id: 123, name: /shopping-cart)
  - resource-timing-z (name: app.js, navigation: 123)
  - resource-timing-y (name: styles.css, navigation: 123)
- navigation-timing: page-load-b (id: 456, name: /shopping-cart)
  - resource-timing-x (name: app.js, navigation: 456)
  - resource-timing-w (name: styles.css, navigation: 456)

Then we could look at each set of navigation timings and understand which page loads were involved and calculate if it's in line with expectations.

## Proposed solution

* calculate an identifier for each navigation timing
* calculate an identifier for each resource timing
* set navigation-timing event id on resource timings to make them discoverable

**Comment by codecapitano** [comment]
They are sent as event which has respective information about the page etc. in it's metas.
So the correlation could be done in the backend instead of putting more load on the web-sdk.

Wdyt?

**Comment by codecapitano** [comment]
Implemented with: #434
