### ISSUE TITLE
Label drop down not sorted alphabetically 

### ISSUE THREAD

**Issue by wardbekker** [grafana/faro-web-sdk#474]
Actual: Label drop down not sorted alphabetically 
Expected: Label drop down sorted alphabetically 

![image](https://github.com/grafana/faro-web-sdk/assets/35603/f824c32e-f376-44d3-b2b8-17262ff25ad7)

**Comment by codecapitano** [comment]
Thank you @wardbekker 

But this Repo is only for the web-sdk.

This issue is for the frontend-o11y plugin.

Cheers 👋

**Comment by codecapitano** [comment]
Adding `wontfix` label because this issue belongs to frontend-o11y plugin.
