### ISSUE TITLE
Create OpenTelemetry trace Sampler taking Faro sampling decisions into account

### ISSUE THREAD

**Issue by cedricziel** [grafana/faro-web-sdk#480]
## Description

Currently, Faro has a probabilistic sampler, but when tracing is enabled, the sampling decision is not promoted to the OpenTelemetry-JS tracer.

The implication is that when the SDK has chosen not to sample, the Otel tracer will still propagate the desire to sample downstream, creating undesired side-effects for parentbased_always_off scenarios.

## Proposed solution

- [x] Create a sampler that takes the initial, global sampling decision into account
- [x] Create a faro event for otel traces, which contains the traceId alongside other useful information so we have the request visible in the user-journey

**Comment by codecapitano** [comment]
Some hints to get started:

* [ParentBased sampler decorator](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#parentbased)

Where to look
<img width="2672" alt="Screenshot 2024-02-14 at 15 56 19" src="https://github.com/grafana/faro-web-sdk/assets/47627413/79e9dcc3-3135-49ec-9132-0739d1a6ed61">

**Comment by cedricziel** [comment]
Additional context:

An event should be created for every kind=client span as is demarcates one interaction with a backend.
