### ISSUE TITLE
Is the API open source?

### ISSUE THREAD

**Issue by veeral-patel** [grafana/faro-web-sdk#487]
Great work with Faro - I'm a huge fan.

However, I'm not sure how to go about using Faro's web SDK without Grafana Cloud - is this possible?

Let's say I can't use Grafana Cloud, is there any way I can get value out of Faro?

**Comment by codecapitano** [comment]
Hi @veeral-patel 

> Great work with Faro - I'm a huge fan.
Awesome that's wonderful feedback, will share it with the team 🙏 

> However, I'm not sure how to go about using Faro's web SDK without Grafana Cloud - is this possible?
Yes it is, the Grafana Agent supports Faro as well. 
Good to know: 
Main focus is on the Faro cloud receiver and the Agent has a different release schedule.
This means sometimes new features are not available at the same time.

Faro also provides a [transport which converts the Faro protocol to Open Telemetry protocol](https://www.npmjs.com/package/@grafana/faro-transport-otlp-http) so you can use Otel collectors as well. 
We even have [users which use Faro to send data to other vendors products using otlp](https://github.com/grafana/faro-web-sdk/issues/430). 

> Let's say I can't use Grafana Cloud, is there any way I can get value out of Faro?
Yes :)

A good place to get started is to have a look at the [Faro demo](https://github.com/grafana/faro-web-sdk/tree/main/demo) which uses the Grafana Agent.
I's also worth it to have a look at the [Faro community Slack channnel](https://grafana.slack.com/archives/C048UH68BM5). There are a lot of people using the Grafana Agent.

Cheers,
Marco

cc @cedricziel

**Comment by codecapitano** [comment]
> Would we have a log for each event like a page view or HTTP request? That's what I'd like. (Don't care as much about console logs)

Mostly yes, to get insight into HTTP requests you can either use our own [fetch](https://www.npmjs.com/package/@grafana/faro-instrumentation-fetch) and [xhr](https://www.npmjs.com/package/@grafana/faro-instrumentation-xhr) instrumentation or the web-tracing package, which uses otel under the hood, to instrument fetch and xhr.

Note: 
our own instrumentations are in development and will be move from experimental to stable in the next 3 month.

Here are some of the things Faro captures automatically:
* Errors: unhandled exceptions and rejected promises which are not handled.
* Web-Vitals
* Performance Timeline data like load and rendering performance of resources/navigations (page loads)
* Captures console.errors
* Auto creates sessions
* ...

> How does the Faro > OTLP package work

Faro has its own protocol so it can produce very small payloads (we are constantly working on reducing the size).
These payloads can be read and understand by the Faro cloud receiver and the Grafana agent but not by otel collectors.

So, to be able to ingest data with an otel collector, the Faro [otlp-http-transport](https://www.npmjs.com/package/@grafana/faro-transport-otlp-http) simply transforms a Faro payload to an otlp compatible payload before sending it. 


> What's the difference between using Faro > OLTP and just using Faro's built in tracing library

**using Faro's built in tracing library**
Faro doesn't have a built-in tracing library. To get tracing, the [web-tracing package](https://www.npmjs.com/package/@grafana/faro-web-tracing) has to be added.

The [web-tracing package](https://www.npmjs.com/package/@grafana/faro-web-tracing) aims to make the setup and usage of otel a bit easier and to get a useful set of default instrumentations.

Data emitted by that instrumentation is wrapped in a standard Faro payload.
Means Faro keeps sending Faro beacons, even if they contain otel traces and spans.

**using Faro > OLTP**
When using the otlp transport Faro transforms all payloads to otlp  before sending it.


Cheers,
Marco
