### ISSUE TITLE
API call using curl for flow mode

### ISSUE THREAD

**Issue by jinaldesailive** [grafana/faro-web-sdk#492]
## Description

I'm testing Grafana faro flow mode.
I've setup locally Grafana Faro using flow mode documentation in docker.
https://grafana.com/docs/agent/latest/flow/setup/install/docker/

Surprisingly I can't call it's /collect endpoint using curl command. I guess it's not exposed, or I'm doing something wrong.

curl http://localhost:12345/collect

Can someone guide me?

**Comment by codecapitano** [comment]
Hi @jinaldesailive in this case it's best to talk to the Agent team.
Best place to start would be the community slack or the forum. 

Cheers,
Marco
