### ISSUE TITLE
Add response status to faro resource event FaroResourceTiming

### ISSUE THREAD

**Issue by ColinRosati** [grafana/faro-web-sdk#525]
## Description

Add response status to faro resource event `FaroResourceTiming`. This would be really helpful to create metrics based on specific http statuses

## Proposed solution

We already have resource status available in scope https://github.com/grafana/faro-web-sdk/blob/c33caee495826c6c73443114c791ef2158af15ef/packages/web-sdk/src/instrumentations/performance/performanceUtils.ts#L47

Prosed solution would be to add one more field `responseStatus`

<details>
  <summary>Proposal</summary>
  
  ### packages/web-sdk/src/instrumentations/performance/performanceUtils.ts
  ```js
export function calculateFaroResourceTiming(resourceEntryRaw: PerformanceResourceTiming): FaroResourceTiming {
  const {
    connectEnd,
    connectStart,
    decodedBodySize,
    domainLookupEnd,
    domainLookupStart,
    duration,
    encodedBodySize,
    fetchStart,
    initiatorType,
    name,
    nextHopProtocol,
    redirectEnd,
    redirectStart,
    // @ts-expect-error the renderBlockingStatus property is not available in all browsers
    renderBlockingStatus: rbs,
    requestStart,
    responseEnd,
    responseStart,
    // @ts-expect-error the renderBlockingStatus property is not available in all browsers
    responseStatus, // responseStatus already available to use
    secureConnectionStart,
    transferSize,
    workerStart,
  } = resourceEntryRaw;

  return {
    name: name,
    duration: toFaroPerformanceTimingString(duration),
    tcpHandshakeTime: toFaroPerformanceTimingString(connectEnd - connectStart),
    dnsLookupTime: toFaroPerformanceTimingString(domainLookupEnd - domainLookupStart),
    tlsNegotiationTime: toFaroPerformanceTimingString(requestStart - secureConnectionStart),
    responseStatus, // <------------- add here new responseStatus field with any normalization
    redirectTime: toFaroPerformanceTimingString(redirectEnd - redirectStart),
    requestTime: toFaroPerformanceTimingString(responseStart - requestStart),
    responseTime: toFaroPerformanceTimingString(responseEnd - responseStart),
    fetchTime: toFaroPerformanceTimingString(responseEnd - fetchStart),
    serviceWorkerTime: toFaroPerformanceTimingString(fetchStart - workerStart),
    decodedBodySize: toFaroPerformanceTimingString(decodedBodySize),
    encodedBodySize: toFaroPerformanceTimingString(encodedBodySize),
    cacheHitStatus: getCacheType(),
    renderBlockingStatus: toFaroPerformanceTimingString(rbs) as FaroResourceTiming['renderBlockingStatus'],
    protocol: nextHopProtocol,
    initiatorType: initiatorType,

    // TODO: add in future iteration, ideally after nested objects are supported by the collector.
    // serverTiming: resourceEntryRaw.serverTiming,
  };
```

</details>

## Context

Faro [docs](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/faro-web-sdk/performance-instrumentation/) say we are using this spec which include responseStatus https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/responseStatus

It is confusion that we are missing this field

**Comment by codecapitano** [comment]
Hey @ColinRosati great suggestion that makes a lot sense. Thanks you for that!

Do you would like to implement it / make a contribution? Otherwise I can quickly tackle it today because the change isn't bug and I can include it in this weeks release.

Cheers,
Marco

**Comment by codecapitano** [comment]
@ColinRosati Any other feedback about the instrumentation is highly  welcome.
It's a very opinionated implementation so feedback is amazingly helpful.

Cheers,
Marco

**Comment by ColinRosati** [comment]
Hey @codecapitano I would love to push the suggestion. Let me open a PR for this one 🙌

**Comment by codecapitano** [comment]
> Hey @codecapitano I would love to push the suggestion. Let me open a PR for this one 🙌

Great, thank you so much 🚀 
I'll take of the docs then.

PS:
Please also update the changelog (slips through quite often)

**Comment by ColinRosati** [comment]
@codecapitano Looks like CI is blocked and says to contact admin. Are you able to help there?
