### ISSUE TITLE
disable logs/events

### ISSUE THREAD

**Issue by imrishuroy** [grafana/faro-web-sdk#539]
Can we have a disable func to turn off sending logs and events completely, without refreshing the browser

**Comment by codecapitano** [comment]
hi @imrishuroy 
you can call `faro.pause()` which will stop Faro sending signals.

Cheers,
Marco

**Comment by imrishuroy** [comment]
> hi @imrishuroy you can call `faro.pause()` which will stop Faro sending signals.
> 
> Cheers, Marco

It worked, is there any way we can start logs/events again without init SDK because when I initialize SDK again it gives me this error **"faro is already registered? Either add instrumentations, transports, etc. to the global faro instance or use the "isolate" property"**

**Comment by codecapitano** [comment]
Hi @imrishuroy, yes can enable Faro sending events again with `faro.unpause()`

Cheers,
Marco

PS:
We definitely should document this better, thanks for the question 🙏

**Comment by imrishuroy** [comment]
> Hi @imrishuroy, yes can enable Faro sending events again with `faro.unpause()`
> 
> Cheers, Marco
> 
> PS: We definitely should document this better, thanks for the question 🙏

Yes please, I struggled a lot, but the solution was quite easy
BTW, thanks a lot, it helped me a lot ❤️
