### ISSUE TITLE
Report INP as well as FID

### ISSUE THREAD

**Issue by jcarres-mdsol** [grafana/faro-web-sdk#557]
## Description

According to [this article](https://web.dev/articles/vitals) the INP web vital is stable and solves issues with the FID vital.
FID is now deprecated.

I imagine only relatively newer browsers would be supporting INP so maybe for a while Faro should report both till support is widespread, dashboards have been migrated, etc.

**Comment by codecapitano** [comment]
Hi @jcarres-mdsol 
Faro is sending both. 
We didn't remove FID.

https://github.com/grafana/faro-web-sdk/blob/38a422e0882084d2f878d18639e6bc2c1c6f40a1/packages/web-sdk/src/instrumentations/webVitals/instrumentation.ts#L9

**Comment by jcarres-mdsol** [comment]
You are absolutely right, I did not check, sorry for the noise

**Comment by codecapitano** [comment]
No worries. Thanks for asking and of course your interest in using Faro 🙏  

Cheers, 
Marco
