### ISSUE TITLE
Grafana Faro ingesting PII? (Session ID against GDPR Compliance) 

### ISSUE THREAD

**Issue by neillua** [grafana/faro-web-sdk#599]
## Description

I head read your documentation on [Data Privacy in Frontend Observability](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/data-privacy/), and I see there are no Cookies. But on a separate note, I see on my logs that Grafana Faro creates a Session ID (which I believe is a randomly generated ID that is used to stitch together the data that are being ingested), but what we are worried about is that will this be traceable back to specific users? (as we will end up having this on public-facing sites, so GDPR compliance would be a hard requirement)

**Comment by cedricziel** [comment]
Hi @neillua ,

Please consult a data privacy specialist that is familiar with your regulatory setting to help you evaluate this in more details. 

Faro does not collect any PII out of the box. And the random ID cannot be tracked back to individuals.

Hope that helps :)

**Comment by neillua** [comment]
Heya @cedricziel,

This is clear. As long as Faro does not collect cookies (as per documentation), and the Session ID on the Faro logs are randomly generated IDs and cannot be tracked back to individuals (as confirmed by you), we should be good so far.

Many thanks! :D
