### ISSUE TITLE
Add Option to Suppress Logs from Being Displayed in Console by ConsoleInstrumentation

### ISSUE THREAD

**Issue by vitebo** [grafana/faro-web-sdk#607]
## Description

Currently, when a log is triggered in the application, it is captured and sent to Alloy by `ConsoleInstrumentation`. The issue is that this log continues to be displayed in the console, making some information more visible than we would prefer.

Would it make sense to create an option to prevent this behavior?

## Proposed Solution

If an option is created, we can simply [add a conditional here](https://github.com/grafana/faro-web-sdk/blob/main/packages/web-sdk/src/instrumentations/console/instrumentation.ts#L28).

I am willing to open a PR with this modification if it makes sense.

**Comment by codecapitano** [comment]
I don't think Faro should be use to hide logs in the browsers console.
Imho it's up to the developers to remove logs before release. 

@cedricziel wdyt? Are you aware of any similar requests?

**Comment by vitebo** [comment]
To clarify the problem:

Removing the logs before release means they won’t be available in Grafana.

The goal is to achieve the same behavior as the `faro.api.pushLog` API but in a way that is transparent to developers, so they don’t need to change their current logging methods.

**Comment by vitebo** [comment]
I understand your point, it really seems to make sense. I think we can consider this issue as resolved then.
