### ISSUE TITLE
`web-vitals` is undefined

### ISSUE THREAD

**Issue by tiennguyen1293** [grafana/faro-web-sdk#620]
## Description

- `web-vitals` has been imported but all methods are undefined, please see the image below.

Please help me to investigate

## Steps to reproduce
- trigger `initializeFaro` will face the issue

```
import { trace, context } from '@opentelemetry/api'
import {
  ReactIntegration,
  ReactRouterHistory,
  ReactRouterVersion,
  initializeFaro as coreInit,
  getWebInstrumentations,
} from '@grafana/faro-react'
import {
  FaroSessionSpanProcessor,
  FaroTraceExporter,
  TracingInstrumentation,
} from '@grafana/faro-web-tracing'

export const initializeFaro = () => {
  const faro = coreInit({
    url: config.FARO_URL,
    apiKey: config.FARO_API_KEY,
    app: {
      name: packageJSON.name,
      version: packageJSON.version,
    },
    sessionTracking: {
      enabled: true,
      samplingRate: 0.25,
    },
    instrumentations: [
      ...getWebInstrumentations({
        captureConsole: true,
      }),

  
      new TracingInstrumentation({
        instrumentationOptions: {
          propagateTraceHeaderCorsUrls: [], 
        },
      }),
      new ReactIntegration({
        router: {
          version: ReactRouterVersion.V4,
          dependencies: {
            history: history as ReactRouterHistory, 
            Route,
          },
        },
      }),
    ],
  })

   faro?.api.pushLog(['Faro was initialized'])
   faro?.api.initOTEL(trace, context)
  
   return faro
 }
```

## Expected behavior

- Worked 

## Actual behavior

![image](https://github.com/grafana/faro-web-sdk/assets/26110369/9bc2f69e-764a-41fe-a035-62b02b91fb78)

![image](https://github.com/grafana/faro-web-sdk/assets/26110369/80191e04-4ce4-4df6-9777-fb90c437097e)

## Environment
 "@grafana/faro-react": "^1.3.8",
 "@grafana/faro-web-tracing": "^1.3.8",
 "react": "^18.3.1",

 Node@20.13.1

**Comment by codecapitano** [comment]
Hi @tiennguyen1293 first time I see this and unfortunately can't reproduce the error.

* Do you use Faro with a standard react web-app or maybe with some mobile framework?
* Do you use the CDN version or the NPM package?
* When/where do you initialize Faro? 
* Since you set to auto update Faro to the most current minor or patch version I assume you are on the most recent Faro version which is 1.7.3 ?

**Comment by tiennguyen1293** [comment]
Hi @codecapitano thank for quick response:
 - I'm using react web-app.
 - use NPM package.
 - when init Web-app I will initialize Faro.
 - I tried upgrade to the latest 1.7.3 version but it has the same issue.

**Comment by codecapitano** [comment]
Ok thanks.

The issue happens during build right?

If yes, can you wipe `node_modules` and install and build again (i know not the coolest answer but I want to exclude that kind of issues)

**Comment by tiennguyen1293** [comment]
the issue happens during runtime.

I ran `rm -rf node_modules yarn.lock` and re-install. And then re-started the App, but the issue still happens.

**Comment by codecapitano** [comment]
* Does it happen on every browser?
* Is there maybe something running which prevents the script to work? Like a content filter?
* Maybe an issue in regards to content security policy?

**Comment by tiennguyen1293** [comment]
it is happening to build runtime to run App on localhost. Maybe it is related to building library or compiling code?

**Comment by codecapitano** [comment]
Aaah at build runtime 👍 

> Maybe it is related to building library or compiling code?

Ok yeah this might be causing the issue. 

What is your build tool of choice?

**Comment by tiennguyen1293** [comment]
i'm using Webpack version 5

**Comment by tiennguyen1293** [comment]
i found the root cause, it is related to webpack config.

I configured
```
resolve.mainFields: ['browser', 'main', 'module'],
```

I will close this issue

Thanks for you support

**Comment by codecapitano** [comment]
Great thank you for the update. 🙏
