### ISSUE TITLE
Infinite API calls due to multiple Faro instances in Micro-Frontend setup

### ISSUE THREAD

**Issue by ValeraKorovelkov** [grafana/faro-web-sdk#671]
We are using a single-spa micro-frontend infrastructure in our project and are in the process of migrating from Datadog to Grafana. We intend to instrument each of our micro frontends (MFEs) and the root app with the Faro SDK.

After I instrumented both the MFE and the root app, I encountered an issue: when both instances are running on the same page, an infinite loop of collector API calls is created, which seems to be related to trace and performance data collection.
MFE configuration
```
const instrumentationOptions = {
      propagateTraceHeaderCorsUrls: [
          new RegExp(REGEXP),
      ],
 };
initializeFaro({
    url: API_URL,
    app: {
        name: APP_NAME,
        version: APP_VERSION,
        environment: NODE_ENV,
    },
    isolate: true,
    instrumentations: [
        ...getWebInstrumentations(),
        new TracingInstrumentation({ instrumentationOptions }),
        new ReactIntegration({
            router: createReactRouterV6DataOptions({
                matchRoutes,
            }),
        }),
    ],
});
```

Root App configuration
```
const instrumentationOptions = {
      propagateTraceHeaderCorsUrls: [
          new RegExp(REGEXP),
      ],
 };
 initializeFaro({
    url: API_URL,
    app: {
        name: APP_NAME,
        version: APP_VERSION,
        environment: NODE_ENV,
    },
    isolate: true,
    instrumentations: [
        ...getWebInstrumentations(),
        new TracingInstrumentation({ instrumentationOptions }),
        new ReactIntegration({
            router: createReactRouterV5Options({
                history,
                Route,
            }),
        }),
    ],
});
```

When I remove the `TracingInstrumentation` and set `enablePerformanceInstrumentation: false` in `getWebInstrumentations` in either the root app or MFE, the issue is resolved. However, this doesn’t seem like a proper solution.

**Comment by codecapitano** [comment]
Hi @ValeraKorovelkov am I right that the both instances use different collector endpoints?

A Faro instance automatically excludes it's own collector URL from tracking.
I have the impression that we have a case where the two Faro instances are tracking each other.

Faro provides the [`ignoreUrls` property where you can define those endpoints which should be excluded from tracking](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/instrument/exclude-endpoints/).
Would you mind testing if it solves your problem when you exclude the endpoint URL of the root app in the the MFE and the MFE endpoint url in the root app?

**Comment by ValeraKorovelkov** [comment]
It helped. Thank you very much!

**Comment by codecapitano** [comment]
> It helped. Thank you very much!

Awesome.
We need to update our docs to reflect that better.

Thanks a lot for reporting @ValeraKorovelkov 🙏
