### ISSUE TITLE
What is the right license ?

### ISSUE THREAD

**Issue by devnewton** [grafana/faro-web-sdk#70]
[LICENSE file ](https://github.com/grafana/faro-web-sdk/blob/main/LICENSE) => Apache 2
[LICENSING.md](https://github.com/grafana/faro-web-sdk/blob/main/LICENSING.md) => AGPL

**Comment by Joibel** [comment]
AGPL is surely too invasive for this to be useful for any commercial user.

**Comment by domasx2** [comment]
It's Apache v2. Thanks for bringing it up!
