### ISSUE TITLE
Module '"@grafana/faro-react"' has no exported member 'createBrowserRouter'.

### ISSUE THREAD

**Issue by omar-zahid** [grafana/faro-web-sdk#700]
## Description

Module '"@grafana/faro-react"' has no exported member 'createBrowserRouter'. [2305]

## Steps to reproduce

Using the following guide for react router v6 data router: 
https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/instrument/faro-react/v6-data-router/

## Expected behavior

As per the example, `createBrowserRouter` should be imported from "@grafana/faro-react"

## Actual behavior

Module '"@grafana/faro-react"' has no exported member 'createBrowserRouter'. [2305]

## Environment

- **SDK version: 1.10.2**
- **SDK instrumentations: React**
- **Device type: N/A**
- **Device name: N/A**
- **OS: Linux**
- **Browser: N/A**

**Comment by codecapitano** [comment]
Hi @omar-zahid 

Thanks a lot. This a mistake in the docs.
`createBrowserRouter` is a [react router component](https://reactrouter.com/en/main/routers/create-browser-router) and is not exported by Faro.
I am going to update the docs.

**Comment by codecapitano** [comment]
Fixed with https://github.com/grafana/faro-web-sdk/pull/701
