### ISSUE TITLE
[Bug] page_id is set to "/*" for URLs other the "english words"

### ISSUE THREAD

**Issue by undefinedhuman** [grafana/faro-web-sdk#702]
## Description

When integrating the very basic Faro implementation into my VueJS frontend (see sample config below) - and have routes defined via "vue-router" other then english words (such as /servers, /networks, /houses), the page_id setting is always set to "/*". Is there any way to configure this?

```typescript filename=sample.ts
initializeFaro({
  url: 'https://faro-collector-prod-eu-west-2.grafana.net/collect/<app-id>',
  app: {
    name: 'Sample',
    version: '1.0.0',
    environment: 'developement'
  },

  instrumentations: [
    ...getWebInstrumentations({
      enablePerformanceInstrumentation: true
    }),

    // Tracing package to get end-to-end visibility for HTTP requests.
    new TracingInstrumentation()
  ]
});
```

## Environment

- **SDK version:**
- **SDK instrumentations:** Web SDK
- **Device type:** Desktop
- **Device name:** Desktop PC, Manjaro
- **OS:** Manjaro
- **Browser:** Firefox 131

## Screenshots

![Image](https://github.com/user-attachments/assets/b47d8713-dc39-499f-a46a-4fdd584a7ad6)

**Comment by codecapitano** [comment]
Hi @undefinedhuman need to investigate whats going on there. 

There's a way to set own pageIDs but it's not that easy to find. We'll improve this in future releases. 

Currently you can archive this with overwriting the page meta.

**Example**
```ts
initializeFaro({
   // ....
    metas: [
      () => ({
        page: {
          id: parsePageId(location.pathname),
          url: location.href,
          attributes: {
            foo: 'bar',
          },
        },
      }),
    ],
// ...
})
```

Maybe this can help you as a workaround for now?

Cheers,
Marco

**Comment by undefinedhuman** [comment]
That works! Thank you very much!

As for my research: I found out if I use "regular" words it works, I first noticed it because my Entity URLs contain the UUID of the entity. So for example:

`/servers` => page_id: /servers
`/servers/UUID` => page_id: /servers/*

And for non english nouns I would say it would also convert the page_id to /*

If you need more information about the setup or if I should setup a minimal example please let me know!

**Comment by codecapitano** [comment]
Hey @undefinedhuman thank you for opening the issue  and your PR as well 🙏 

The page_id parsing happens in the Faro receiver.

The parser's gibberish detector is based on a likeliness of two letters being next to each other in western European languages, so for example "abc" is gibberish because it doesn't happen often in words. 

The parser is working as expected and the page_id can be overridden cia the page_id meta in Faro itself.

Closing the issue for now.
