### ISSUE TITLE
Converting circular structure to JSON error when pushing some error logs

### ISSUE THREAD

**Issue by raphaelquati** [grafana/faro-web-sdk#729]
## Description

I'm using iife modules (in a Angular 6 application).

## Environment

- **SDK 1.11.0**
- **SDK instrumentations: Web SDK, Web Tracing**
- **OS: Windows 11*
- **Browser: Edge**

Javascript console:
```
 @grafana/faro-web-sdk:instrumentation-console
 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'element' -> object with constructor 'Object'
    |     property 'componentProvider' -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at faro-web-sdk.iife.js:1:41494
    at Array.map (<anonymous>)
    at x.filter.forEach.console.<computed> [as error] (faro-web-sdk.iife.js:1:41470)
    at Object.ca [as factory] (main.62067dc830e2ab5a2304.js:1:17449849)
    at n.logError (main.62067dc830e2ab5a2304.js:1:5713175)
    at n.handleError (main.62067dc830e2ab5a2304.js:1:5604401)
    at main.62067dc830e2ab5a2304.js:1:5632917
    at i.invoke (faro-web-tracing.iife.js:7:25981)
    at r.run (faro-web-tracing.iife.js:7:21270)
    at n.runOutsideAngular (main.62067dc830e2ab5a2304.js:1:5623151)
    at n.tick (main.62067dc830e2ab5a2304.js:1:5632860)
    at main.62067dc830e2ab5a2304.js:1:5631037
    at i.invoke (faro-web-tracing.iife.js:7:25981)
    at Object.onInvoke (main.62067dc830e2ab5a2304.js:1:5622120)
```

The error occurs here:
![Image](https://github.com/user-attachments/assets/a24b68dd-b13f-4bda-ab30-2fb7148d6687)

I think is related to https://github.com/grafana/faro-web-sdk/issues/587

The error (angular error):

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: true'. Current value: 'ngIf: false'
```

**Comment by codecapitano** [comment]
Thanks for reporting @raphaelquati.
We'll release a fix today.

**Comment by AdityaRanjanSingh** [comment]
Hi,

I ran into the same issue today.
I am using    ` "@grafana/faro-web-sdk": "^1.12.0",`
Is the fix already released 
![Image](https://github.com/user-attachments/assets/543504db-3211-47b2-ad70-90df7d26886b)

**Comment by raphaelquati** [comment]
I've updated my application to use 1.12.0 (I'm using iife modules), and the error was gone.

**Comment by codecapitano** [comment]
@AdityaRanjanSingh 

I see the issue.
There's a stringifier left which is not protected. 

We'll release a hotfix tomorrow.

**Comment by codecapitano** [comment]
For reference: fixed [here](https://github.com/grafana/faro-web-sdk/pull/742)
