### ISSUE TITLE
Demo does not run on Windows

### ISSUE THREAD

**Issue by EddeCCC** [grafana/faro-web-sdk#77]
Hello,

I´ve tried to run the demo application with Docker on Windows 10.

I cloned the whole repository and after I´ve run 'docker compose --profile demo up' all Docker containers have been created. However, there not able to start.

I get the following error message:
Error response from daemon: failed to mount local volume: mount /demo/logs:/var/lib/docker/volumes/faro-web-sdk_demo_demo_logs/_data, flags: 0x1000: no such file or directory

Even though the directory '/demo/logs' exists inside the repository.

I´ve also tried to run the demo on MacOS and everything was fine, so I guess the reason for the problem is Windows.
I believe something is wrong with the paths, but I couldn´t figure out where exactly the problem is.

Would be great if someone could solve this problem.

Cheers

**Comment by EddeCCC** [comment]
Hi @bfmatei ,
thanks for your quick response.

I hardcoded the absolute path in line 139 and had to comment out line 60.
After that everything worked.

Thank you.

**Comment by bfmatei** [comment]
Marking this as solved.
