### ISSUE TITLE
TracingInstrumentation breaks fetch requests

### ISSUE THREAD

**Issue by bfmatei** [grafana/faro-web-sdk#79]
## Description

When using `TracingInstrumentation`, `fetch` requests with relative URLs are broken in sub-pages.

## Steps to reproduce

1. Add Faro Web SDK and `TracingIntrumentation` to the project
2. Add a `fetch` request with a relative URL
3. Navigate to a sub-page
4. Observe the `fetch` request

## Expected behavior

The request will be executed without any issue.

## Actual behavior

The request has a tampered URL relative to the sub-page.

## Environment

- **SDK version:** 1.0.0-beta3
- **SDK instrumentations:** Web SDK, Web Tracing
- **Device type:** all
- **Device name:** all
- **OS:** all
- **Browser:** all

**Comment by domasx2** [comment]
Fixed in opentelemetry.js via https://github.com/open-telemetry/opentelemetry-js/pull/3670 and released wih 1.11.0

**Comment by domasx2** [comment]
web-tracing needs to pull newer version of otel
