### ISSUE TITLE
ReferenceError: exports is not defined in ES module scope

### ISSUE THREAD

**Issue by rexwangcc** [grafana/faro-web-sdk#82]
## Description

Hi folks! We got 

```
event - compiled client and server successfully in 261 ms (3557 modules)
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '....../node_modules/@grafana/faro-web-tracing/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

at file:///...../node_modules/@grafana/faro-web-tracing/dist/cjs/index.js:2:23

```

when trying to integrate faro with our nextjs + TS application. The setup is rather simple, as we just imported several stuff following the readme:

```js
import { initializeFaro } from '@grafana/faro-web-sdk';
import {
  FaroSessionSpanProcessor,
  FaroTraceExporter,
} from '@grafana/faro-web-tracing';
```

## Expected behavior

It should not cry like this?

## Environment

- **SDK version:**
```
"@grafana/faro-core": "^1.0.0-beta4",
"@grafana/faro-web-sdk": "^1.0.0-beta4",
"@grafana/faro-web-tracing": "^1.0.0-beta4",
```
- **SDK instrumentations:**
- **Device type:**
- **Device name:**
- **OS:** Ubuntu 2204
- **Browser:** Chrome stable

## Context

I tracked it all the way back to https://github.com/grafana/faro-web-sdk/pull/27, but found nothing really helpful to this issue.

Thanks!

**Comment by bfmatei** [comment]
Hey! Thank you for opening this.

I fixed this in #83 and version `1.0.0-beta5` will be released today with the fix included.
