### ISSUE TITLE
TracingInstrumentation breaks Faro initialization.

### ISSUE THREAD

**Issue by rexwangcc** [grafana/faro-web-sdk#86]
## Description

Hi Folks! I'm trying to initialize Faro within our NextJs based application and run into:

```
TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at ZoneAwarePromise.then (<anonymous>)
    at node:internal/per_context/primordials:440:35
    at new Promise (<anonymous>)
    at new SafePromise (node:internal/per_context/primordials:408:29)
    at node:internal/per_context/primordials:440:9
    at Array.map (<anonymous>)
    at arrayToSafePromiseIterable (node:internal/per_context/primordials:437:5)
    at node:internal/per_context/primordials:453:21
    at new Promise (<anonymous>)
    at primordials.SafePromiseAll (node:internal/per_context/primordials:452:3)
    at ESMLoader.import (node:internal/modules/esm/loader:530:30)
    at importModuleDynamically (node:internal/modules/cjs/loader:1098:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:21)
    at importModuleDynamically (node:vm:389:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    .....
    at Object.<anonymous> (...../.next/server/pages/_app.js:2584:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
```

```ts
import {
  ErrorsInstrumentation,
  WebVitalsInstrumentation,
  initializeFaro as coreInit,
} from '@grafana/faro-web-sdk';
import { TracingInstrumentation } from '@grafana/faro-web-tracing';

const initializeFaro = () => {
  const faro = coreInit({
    url: composeOTELCollectorString(),
    // apiKey: 'secret',
    app: {
      name:
        `some-trivial-app,
      version: '0.0.0',
      environment: process.env.NEXT_PUBLIC_ENV,
    },
    instrumentations: [
      new ErrorsInstrumentation(),
      new WebVitalsInstrumentation(),
      new TracingInstrumentation(),
    ],
    // transports: [new ConsoleTransport()],
    session: undefined,
  });

  return faro;
};
```

It works fine as long as we don't try to register `TracingInstrumentation`, which is a must have in our use case. Any ideas?

## Environment

- **SDK version:**

```
"@opentelemetry/api": "^1.3.0",
"@opentelemetry/auto-instrumentations-node": "^0.35.0",
"@opentelemetry/auto-instrumentations-web": "^0.31.0",
"@opentelemetry/context-zone": "^1.8.0",
"@opentelemetry/sdk-node": "^0.34.0",
"@grafana/faro-core": "^1.0.0-beta4",
"@grafana/faro-web-sdk": "^1.0.0-beta4",
"@grafana/faro-web-tracing": "^1.0.0-beta5",
"next": "12.3.1"
...
```

with `node version v18.12.1`

- **SDK instrumentations:**
- **Device type:** PC
- **Device name:**
- **OS:** Ubuntu 2204
- **Browser:** Chrome Stable channel

**Comment by bfmatei** [comment]
Hello!

Can you please fill in the `Environment` and `Steps to reproduce` sections?

I just tried it out on the latest version of Next.js boilerplate (`npx create-next-app@latest`) and it works out fine in my case. I didn't add any customizations, just copy-pasted your code with the mention that I had to add a tick after `` `some-trivial-app``.

The code in the `_app.tsx` file:
```ts
import {
  ConsoleTransport,
  ErrorsInstrumentation,
  WebVitalsInstrumentation,
  initializeFaro as coreInit
} from '@grafana/faro-web-sdk';
import { TracingInstrumentation } from '@grafana/faro-web-tracing';

import '../styles/globals.css';
import type { AppProps } from 'next/app';

const initializeFaro = () => {
  const faro = coreInit({
    app: {
      name: `some-trivial-app`,
      version: '0.0.0',
      environment: process.env.NEXT_PUBLIC_ENV
    },
    instrumentations: [new ErrorsInstrumentation(), new WebVitalsInstrumentation(), new TracingInstrumentation()],
    transports: [new ConsoleTransport()],
    session: undefined
  });

  return faro;
};

initializeFaro();

export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}
```

**Comment by rexwangcc** [comment]
> Hello!
> 
> Can you please fill in the `Environment` and `Steps to reproduce` sections?
> 
> I just tried it out on the latest version of Next.js boilerplate (`npx create-next-app@latest`) and it works out fine in my case. I didn't add any customizations, just copy-pasted your code with the mention that I had to add a tick after `` `some-trivial-app ``.
> 
> The code in the `_app.tsx` file:
> 
> ```ts
> import {
>   ConsoleTransport,
>   ErrorsInstrumentation,
>   WebVitalsInstrumentation,
>   initializeFaro as coreInit
> } from '@grafana/faro-web-sdk';
> import { TracingInstrumentation } from '@grafana/faro-web-tracing';
> 
> import '../styles/globals.css';
> import type { AppProps } from 'next/app';
> 
> const initializeFaro = () => {
>   const faro = coreInit({
>     app: {
>       name: `some-trivial-app`,
>       version: '0.0.0',
>       environment: process.env.NEXT_PUBLIC_ENV
>     },
>     instrumentations: [new ErrorsInstrumentation(), new WebVitalsInstrumentation(), new TracingInstrumentation()],
>     transports: [new ConsoleTransport()],
>     session: undefined
>   });
> 
>   return faro;
> };
> 
> initializeFaro();
> 
> export default function App({ Component, pageProps }: AppProps) {
>   return <Component {...pageProps} />;
> }
> ```

Thanks for the prompt reply and taking time reproduce the issue! The missing backquote is more like a typo and I'm still running into the same issue. I could try the latest NextJs version (v13) see if i can reproduce it later.

**Comment by rexwangcc** [comment]
Hi, sorry for the delayed reply, I tried the latest nextjs boilerplate code and even though the errors occurred in a different way from what we ran into within our application, it's now reproduce-able:

1. Make sure node version is `v18.12.1` by `node --version` (nvm should help on it).
2. Use `npx create-next-app@latest` to initialize the boilerplate with default values, such as a "test" application with TypeScript enabled.
3. Run `npm i @grafana/faro-web-sdk @grafana/faro-core @grafana/faro-web-tracing` to add Faro related dependencies
4. Update the `_app.tsx` to be like:

```tsx
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import {
  ConsoleTransport,
  ErrorsInstrumentation,
  WebVitalsInstrumentation,
  initializeFaro as coreInit,
} from '@grafana/faro-web-sdk';
import { TracingInstrumentation } from '@grafana/faro-web-tracing';


const initializeFaro = () => {
  const faro = coreInit({
    app: {
      name: `some-trivial-app`,
      version: '0.0.0',
      environment: 'dev',
    },
    instrumentations: [
      new ErrorsInstrumentation(),
      new WebVitalsInstrumentation(),
      // new TracingInstrumentation(),
    ],
    transports: [new ConsoleTransport()],
    session: undefined,
  });

  return faro;
};

initializeFaro();

export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}
```
5. Now if you run `npm run dev`, the local dev server should be able to spin up, which is kinda different from what we experience in our application (with nextjs v12)
6. But when you kill the dev server process and take a look at the console, the exact same errors should occur:

```
TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at ZoneAwarePromise.then (<anonymous>)
    at node:internal/per_context/primordials:440:35
    at new Promise (<anonymous>)
    at new SafePromise (node:internal/per_context/primordials:408:29)
    at node:internal/per_context/primordials:440:9
    at Array.map (<anonymous>)
    at arrayToSafePromiseIterable (node:internal/per_context/primordials:437:5)
    at node:internal/per_context/primordials:453:21
    at new Promise (<anonymous>)
    at primordials.SafePromiseAll (node:internal/per_context/primordials:452:3)
    at ESMLoader.import (node:internal/modules/esm/loader:530:30)
    at importModuleDynamically (node:internal/modules/cjs/loader:1098:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:21)
    at importModuleDynamically (node:vm:389:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at Object.loadConfig [as default] (/home/user/Projects/playground/tracing/test/node_modules/next/dist/server/config.js:69:78)
    at async process.handleSessionStop (/home/user/Projects/playground/tracing/test/node_modules/next/dist/cli/next-dev.js:75:24)
```

Not sure if there is anything else I could provide here at the moment, but it would be really appreciated if you have some time help on this :smiley:

**Comment by rexwangcc** [comment]
Update: searching across the web, the closet error report I have found so far is https://github.com/angular/angular/issues/47872 which seems to be related to Node version :thinking:

**Comment by rexwangcc** [comment]
Since this is stale and we have moved on with other approaches, I'd like to close this. Thanks!
