### ISSUE TITLE
OTLP compliant transport

### ISSUE THREAD

**Issue by bfmatei** [grafana/faro-web-sdk#90]
## Description

The current `FetchTransport` uses a proprietary schema for the payload which is not compliant with the OTLP schema.

## Proposed solution

The best approach to this issue is to create another HTTP transport, which we will refer to as `OtlpTransport`.

The `OtlpTransport` should be pretty similar to the current `FetchTransport`, but with an important difference: it should batch multiple events into a single HTTP request rather than sending an HTTP request for each signal. The batching should be configurable by number of signals send in a single request but also by the delay of waiting for a new signal before sending the current one.

For example, let's assume that whenever a signal is sent to a transport, it will wait for another `250ms` (this should be configurable) in order to wait for another signal. If no other signal came, the signal is sent. But if 30 (this should also be configurable) other signals are sent, then we should batch those 30 in a single request and any other subsequent signal will be part of the next batch.

The `OtlpTransport` should also implement the retrying mechanism and concurrency handling mechanism that are currently present in the `FetchTransport`.

As a stretch goal for the `OtlpTransport`, simple sampling should also be implemented. Simple sampling refers to dropping a percentage of the signals unless they are are from certain categories (i.e. errors, error logs or events). This should be disabled by default and it would offer a way for implementing proper sampling in the future.

The `OtlpTransport` will replace the `FetchTransport` as the default transport in `@grafana/faro-web-sdk` but `FetchTransport` should continue to exist for backwards compatibility and Grafana Agent compatibility purposes.

## Context

- [OTLP schema reference](https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto)

**Comment by codecapitano** [comment]
1st PR: [Otel ResourceLogs Payload Transform](https://github.com/grafana/faro-web-sdk/pull/101)

**Comment by codecapitano** [comment]
Open tasks/follow ups:

* [Add OTel compatible Traces transform](https://github.com/grafana/faro-web-sdk/issues/108)
* [Otel compatible Logs and Traces transport](https://github.com/grafana/faro-web-sdk/issues/109)
* [Align measurement payload to only be able to contain exactly one measurement](https://github.com/grafana/faro-web-sdk/issues/110)
