### ISSUE TITLE
docs: Include browser support

### ISSUE THREAD

**Issue by kpelelis** [grafana/faro-web-sdk#96]
## Description

As this will be a library that will run in multiple systems, the documentation should include the list of browsers that the SDK will work on.

## Proposed solution

Run the SDK in an extensive test in different versions of the browsers to verify

**Comment by eskirk** [comment]
@kpelelis @codecapitano are we doing this already? would be nice to have to improve the hardness of the web SDK.

**Comment by codecapitano** [comment]
No, it's planned for this quarter: Add support matrix

**Comment by codecapitano** [comment]
This is a duplicate and covered by: https://github.com/orgs/grafana/projects/238/views/21?pane=issue&itemId=27684210
